// packages/sdks/output/svelte/src/blocks/img.svelte
<script>
    
    
    
    
  import  {  isEditing  }  from '../functions/is-editing';

  


    
    export let backgroundSize;
export let backgroundPosition;
export let attributes;
export let imgSrc;
export let altText;

    
    

    

    

    

    
  </script>

  <img {...attributes} style={{
objectFit: backgroundSize || 'cover',
objectPosition: backgroundPosition || 'center'
}}  key={isEditing() && imgSrc || 'default-key'}  alt={altText}  src={imgSrc}  />

// packages/sdks/output/vue/nuxt2/src/blocks/img/img.vue
<template>
  <img
    v-bind="attributes"
    :style="{
      objectFit: backgroundSize || 'cover',
      objectPosition: backgroundPosition || 'center',
    }"
    :key="(isEditing() && imgSrc) || 'default-key'"
    :alt="altText"
    :src="imgSrc"
  />
</template>
<script>
import { isEditing } from "../../functions/is-editing.js";

export default {
  name: "builder-img-component",

  props: [
    "backgroundSize",
    "backgroundPosition",
    "attributes",
    "imgSrc",
    "altText",
  ],

  data: () => ({ isEditing }),
};
</script>
