// packages/sdks/output/svelte/src/components/render-blocks.svelte
<script>
    
    
    
    
  import  {  isEditing  }  from '../functions/is-editing';
import  RenderBlock,  {  }  from './render-block.svelte';

  


    
    export let blocks;
export let parent;
export let path;

    function onClick() {
if (isEditing() && !blocks?.length) {
  window.parent?.postMessage({
    type: 'builder.clickEmptyBlocks',
    data: {
      parentElementId: parent,
      dataPath: path
    }
  }, '*');
}
}

function onMouseEnter() {
if (isEditing() && !blocks?.length) {
  window.parent?.postMessage({
    type: 'builder.hoverEmptyBlocks',
    data: {
      parentElementId: parent,
      dataPath: path
    }
  }, '*');
}
}
    $: className = () => {
return 'builder-blocks' + (!blocks?.length ? ' no-blocks' : '');
};

    

    

    

    
  </script>

  <div  class="div"  builder-path={path}  builder-parent-id={parent}  dataSet={{
class: className()
}}  on:click="{event => onClick()}"  on:mouseenter="{event => onMouseEnter()}"  class={className()} >
    
{#if blocks }
      
{#each blocks as block, index }<RenderBlock  key={block.id}  block={block} ></RenderBlock>{/each}

    {/if}

  </div>

  <style>
    .div { 
display: flex;
flex-direction: column;
align-items: stretch; }
  </style>

// packages/sdks/output/vue/nuxt2/src/components/render-blocks.vue
<template>
  <div
    class="div-23e8fqt91nf"
    :builder-path="path"
    :builder-parent-id="parent"
    :dataSet="{
      class: className,
    }"
    @click="onClick()"
    @mouseenter="onMouseEnter()"
    :class="_classStringToObject(this.className)"
  >
    <render-block
      v-for="(block, index) in blocks"
      :block="block"
      :key="block.id"
    ></render-block>
  </div>
</template>
<script>
import { isEditing } from "../functions/is-editing.js";
import RenderBlock from "./render-block/render-block";

export default {
  name: "render-blocks",
  components: { "render-block": async () => RenderBlock },
  props: ["blocks", "parent", "path"],

  computed: {
    className() {
      return "builder-blocks" + (!this.blocks?.length ? " no-blocks" : "");
    },
  },

  methods: {
    onClick() {
      if (isEditing() && !this.blocks?.length) {
        window.parent?.postMessage(
          {
            type: "builder.clickEmptyBlocks",
            data: {
              parentElementId: this.parent,
              dataPath: this.path,
            },
          },
          "*"
        );
      }
    },
    onMouseEnter() {
      if (isEditing() && !this.blocks?.length) {
        window.parent?.postMessage(
          {
            type: "builder.hoverEmptyBlocks",
            data: {
              parentElementId: this.parent,
              dataPath: this.path,
            },
          },
          "*"
        );
      }
    },
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>
<style scoped>
.div-23e8fqt91nf {
  display: flex;
  flex-direction: column;
  align-items: stretch;
}
</style>
