// packages/sdks/snippets/nuxt/pages/advanced-child.vue
<script setup lang="ts">
  import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-vue';
  import CustomTabsInfo from '../components/CustomTabsInfo';

  const route = useRoute();
  const model = 'advanced-child';
  const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  const { data: content, pending } = await useAsyncData(
    `builder-${model}-${route.path}`,
    () => fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
          urlPath: route.path,
        },
      })
    );
    </script>

<template>
  <div>
    <div v-if="pending">Loading...</div>
    <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
    <Content
      v-else
      :content="content"
      :model="model"
      :apiKey="apiKey"
      :customComponents="[CustomTabsInfo]"
    />
  </div>
</template>

// packages/sdks/snippets/svelte/src/components/advanced-child/AdvancedChild.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-svelte';
  import type { BuilderContent } from '@builder.io/sdk-svelte';
  import { CustomTabsInfo } from './CustomTabsInfo';

  let loading = true;
  let content: BuilderContent | null;

  let model = 'advanced-child';
  let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  onMount(() => {
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    }).then((data) => {
      content = data;
      loading = false;
    });
  });
</script>

{#if loading}
  <div>Loading...</div>
{:else if !content && !isPreviewing()}
  <div>404 - Not Found</div>
{:else}
  <Content {content} {apiKey} {model} customComponents={[CustomTabsInfo]} />
{/if}
