// packages/sdks/src/components/render-block/render-component-and-styles.lite.tsx
import { TARGET } from '../../constants/target.js';
import { BuilderBlock } from '../../types/builder-block.js';
import BlockStyles from './block-styles.lite';
import RenderBlock from './render-block.lite';
import { For, Show } from '@builder.io/mitosis';

type Props = {
  block: BuilderBlock;
  componentRef: any;
  componentOptions: any;
  blockChildren: BuilderBlock[];
};

export default function RenderComponentAndStyles(props: Props) {
  return (
    <>
      <Show when={TARGET === 'vue' || TARGET === 'svelte'}>
        <BlockStyles block={props.block} />
      </Show>
      {props.componentRef && (
        <props.componentRef {...props.componentOptions}>
          <For each={props.blockChildren}>
            {(child) => <RenderBlock key={child.id} block={child} />}
          </For>
        </props.componentRef>
      )}
    </>
  );
}

// packages/sdks/output/solid/src/components/render-block/render-component-and-styles.lite.tsx
import { Show, For } from "solid-js";
import { Dynamic } from "solid-js/web";

import { TARGET } from "../../constants/target.js";
import BlockStyles from "./block-styles.lite";
import RenderBlock from "./render-block.lite";

function RenderComponentAndStyles(props) {
  return (
    <>
      <Show when={TARGET === "vue" || TARGET === "svelte"}>
        <BlockStyles block={props.block}></BlockStyles>
      </Show>
      <Show when={props.componentRef}>
        <Dynamic {...props.componentOptions} component={props.componentRef}>
          <For each={props.blockChildren}>
            {(child, _index) => {
              const index = _index();
              return <RenderBlock key={child.id} block={child}></RenderBlock>;
            }}
          </For>
        </Dynamic>
      </Show>
    </>
  );
}

export default RenderComponentAndStyles;
