// packages/sdks/output/react-native/src/components/render-block/render-component.lite.tsx
import * as React from "react";
import { View, StyleSheet, Image, Text } from "react-native";
import BlockStyles from "./block-styles.lite";
import RenderBlock from "./render-block.lite";

export default function RenderComponent(props) {
  const ComponentRefRef = props.componentRef;

  return (
    <>
      {props.componentRef ? (
        <>
          <ComponentRefRef {...props.componentOptions}>
            {props.blockChildren?.map((child) => (
              <RenderBlock key={"render-block-" + child.id} block={child} />
            ))}

            {props.blockChildren?.map((child) => (
              <BlockStyles key={"block-style-" + child.id} block={child} />
            ))}
          </ComponentRefRef>
        </>
      ) : null}
    </>
  );
}

// packages/sdks/output/solid/src/components/render-block/render-component.lite.tsx
import { Show, For } from "solid-js";
import { Dynamic } from "solid-js/web";

import BlockStyles from "./block-styles.lite";
import RenderBlock from "./render-block.lite";

function RenderComponent(props) {
  return (
    <Show when={props.componentRef}>
      <Dynamic {...props.componentOptions} component={props.componentRef}>
        <For each={props.blockChildren}>
          {(child, _index) => {
            const index = _index();
            return (
              <RenderBlock
                key={"render-block-" + child.id}
                block={child}
              ></RenderBlock>
            );
          }}
        </For>
        <For each={props.blockChildren}>
          {(child, _index) => {
            const index = _index();
            return (
              <BlockStyles
                key={"block-style-" + child.id}
                block={child}
              ></BlockStyles>
            );
          }}
        </For>
      </Dynamic>
    </Show>
  );
}

export default RenderComponent;
