// packages/sdks/output/angular/src-original/context/builder.context.ts
import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export default class BuilderContext {
  content: any = null;
  context: any = {};
  localState: any = undefined;
  rootSetState() {}
  rootState: any = {};
  apiKey: any = null;
  apiVersion: any = undefined;
  componentInfos: any = {};
  inheritedStyles: any = {};
  BlocksWrapper: any = "div";
  BlocksWrapperProps: any = {};
  nonce: any = "";

  constructor() {}
}

// examples/react-v2/src/sdk-src/context/builder.context.ts
import { createContext } from "react";

export default createContext<any>({
  content: null,
  context: {},
  localState: undefined,
  rootSetState() {},
  rootState: {},
  apiKey: null,
  apiVersion: undefined,
  componentInfos: {},
  inheritedStyles: {},
  BlocksWrapper: "div",
  BlocksWrapperProps: {},
});
