// packages/sdks/snippets/sveltekit/src/routes/advanced-child/CustomTabs.svelte
<script lang="ts">
  import { Blocks, type BuilderBlock } from '@builder.io/sdk-svelte';

  export let builderBlock: BuilderBlock;
  export let tabList: Array<{ tabName: string; blocks: BuilderBlock[] }>;

  let activeTab = 0;
</script>

{#if tabList.length}
  <div class="dynamics-slots">
    {#each tabList as tab, index}
      <button on:click={() => (activeTab = index)}>
        {tab.tabName}
      </button>
    {/each}

    <Blocks
      blocks={tabList[activeTab].blocks}
      path={`tabList.${activeTab}.blocks`}
      parent={builderBlock.id}
    />
  </div>
{/if}

// packages/sdks/snippets/nuxt/components/CustomTabs.vue
<template>
  <div class="dynamics-slots" v-if="tabList.length">
    <button
      v-for="(tab, index) in tabList"
      :key="index"
      :class="{ active: activeTab === index }"
      @click="activeTab = index"
    >
      {{ tab.tabName }}
    </button>

    <Blocks
      :blocks="tabList[activeTab].blocks"
      :path="`tabList.${activeTab}.blocks`"
      :parent="builderBlock.id"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, defineProps } from 'vue';
import { Blocks, type BuilderBlock } from '@builder.io/sdk-vue';

const activeTab = ref(0);

const { builderBlock, tabList } = defineProps<{
  builderBlock: BuilderBlock;
  tabList: Array<{
    tabName: string;
    blocks: BuilderBlock[];
  }>;
}>();
</script>
