// packages/sdks/snippets/react-sdk-next-14-app/app/components/ProductInfo.tsx
export type Product = {
  image: string;
  title: string;
  description: string;
  price: number;
  rating: { rate: number; count: number };
};

export function ProductInfo({ product }: { product: Product }) {
  if (!product) return null;

  return (
    <>
      <div className="product-image">
        <img src={product.image} alt={product.title} />
      </div>
      <div className="product-info">
        <h2>{product.title}</h2>
        <p>{product.description}</p>
        <p>Price: {product.price} $</p>
        <p>Rating: {product.rating.rate} / 5</p>
        <button>Buy now</button>
      </div>
    </>
  );
}

// packages/sdks/snippets/nuxt/components/ProductInfo.vue
<!-- /components/ProductInfo.vue -->
<template>
    <div v-if="product" class="product-info">
      <div class="product-image">
        <img :src="product.image" :alt="product.title" />
      </div>
      <div>
        <h2>{{ product.title }}</h2>
        <p>{{ product.description }}</p>
        <p>Price: {{ product.price }} $</p>
        <p>Rating: {{ product.rating.rate }} / 5</p>
        <button>Buy now</button>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
    defineProps<{
        product: {
        id: number;
        title: string;
        price: number;
        description: string;
        category: string;
        image: string;
        rating: { rate: number; count: number };
        } | null;
  }>();
  </script>
