// packages/sdks/output/angular/src-copy-fast-diff/components/content/content.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

import { getDefaultRegisteredComponents } from "../../constants/builder-registered-components";
import { TARGET } from "../../constants/target";
import ComponentsContext from "../../context/components.context";
import type {
  BuilderContextInterface,
  BuilderRenderState,
  RegisteredComponents,
} from "../../context/types";
import { serializeComponentInfo } from "../../functions/register-component";
import type { ComponentInfo } from "../../types/components";
import type { Dictionary } from "../../types/typescript";
import Blocks from "../blocks/blocks";
import { getUpdateVariantVisibilityScript } from "../content-variants/helpers";
import DynamicDiv from "../dynamic-div";
import InlinedScript from "../inlined-script";
import EnableEditor from "./components/enable-editor";
import ContentStyles from "./components/styles";
import {
  getContentInitialValue,
  getRootStateInitialValue,
} from "./content.helpers";
import type { ContentProps } from "./content.types";
import { wrapComponentRef } from "./wrap-component-ref";

@Component({
  selector: "content-component, ContentComponent",
  template: `
    <enable-editor
      [nonce]="nonce"
      [content]="content"
      [data]="data"
      [model]="model"
      [context]="context"
      [apiKey]="apiKey"
      [canTrack]="canTrack"
      [locale]="locale"
      [enrich]="enrich"
      [showContent]="showContent"
      [builderContextSignal]="builderContextSignal"
      [contentWrapper]="contentWrapper"
      [contentWrapperProps]="contentWrapperProps"
      [trustedHosts]="trustedHosts"
    >
      <ng-container *ngIf="isSsrAbTest">
        <inlined-script
          id="builderio-variant-visibility"
          [scriptStr]="scriptStr"
          [nonce]="nonce || ''"
        ></inlined-script>
      </ng-container>
      <ng-container *ngIf="TARGET !== 'reactNative'">
        <content-styles
          [nonce]="nonce || ''"
          [isNestedRender]="isNestedRender"
          [contentId]="builderContextSignal.content?.id"
          [cssCode]="builderContextSignal.content?.data?.cssCode"
          [customFonts]="builderContextSignal.content?.data?.customFonts"
        ></content-styles>
      </ng-container>
      <blocks
        [blocks]="builderContextSignal.content?.data?.blocks"
        [context]="builderContextSignal"
        [registeredComponents]="registeredComponents"
        [linkComponent]="linkComponent"
      ></blocks>
    </enable-editor>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, EnableEditor, InlinedScript, ContentStyles, Blocks],
})
export default class ContentComponent {
  TARGET = TARGET;

  @Input() content!: ContentProps["content"];
  @Input() data!: ContentProps["data"];
  @Input() locale!: ContentProps["locale"];
  @Input() context!: ContentProps["context"];
  @Input() canTrack!: ContentProps["canTrack"];
  @Input() apiKey!: ContentProps["apiKey"];
  @Input() apiVersion!: ContentProps["apiVersion"];
  @Input() customComponents!: ContentProps["customComponents"];
  @Input() model!: ContentProps["model"];
  @Input() blocksWrapper!: ContentProps["blocksWrapper"];
  @Input() blocksWrapperProps!: ContentProps["blocksWrapperProps"];
  @Input() nonce!: ContentProps["nonce"];
  @Input() enrich!: ContentProps["enrich"];
  @Input() showContent!: ContentProps["showContent"];
  @Input() contentWrapper!: ContentProps["contentWrapper"];
  @Input() contentWrapperProps!: ContentProps["contentWrapperProps"];
  @Input() trustedHosts!: ContentProps["trustedHosts"];
  @Input() isSsrAbTest!: ContentProps["isSsrAbTest"];
  @Input() isNestedRender!: ContentProps["isNestedRender"];
  @Input() linkComponent!: ContentProps["linkComponent"];

  scriptStr = getUpdateVariantVisibilityScript({
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-non-null-asserted-optional-chain
    variationId: this.content?.testVariationId!,
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-non-null-asserted-optional-chain
    contentId: this.content?.id!,
  });
  contentSetState(newRootState: BuilderRenderState) {
    this.builderContextSignal.rootState = newRootState;
  }
  registeredComponents = [
    ...getDefaultRegisteredComponents(),
    ...(this.customComponents?.filter(({ models }) => {
      if (!models?.length) return true;
      if (!this.model) return true;
      return models.includes(this.model);
    }) || []),
  ].reduce<RegisteredComponents>(
    (acc, { component, ...info }) => ({
      ...acc,
      [info.name]: {
        component: component,
        ...serializeComponentInfo(info),
      },
    }),
    {}
  );
  builderContextSignal = {
    content: getContentInitialValue({
      content: this.content,
      data: this.data,
    }),
    localState: undefined,
    rootState: getRootStateInitialValue({
      content: this.content,
      data: this.data,
      locale: this.locale,
    }),
    rootSetState: this.contentSetState.bind(this),
    context: this.context || {},
    canTrack: this.canTrack,
    apiKey: this.apiKey,
    apiVersion: this.apiVersion,
    componentInfos: [
      ...getDefaultRegisteredComponents(),
      ...(this.customComponents?.filter(({ models }) => {
        if (!models?.length) return true;
        if (!this.model) return true;
        return models.includes(this.model);
      }) || []),
    ].reduce<Dictionary<ComponentInfo>>(
      (acc, { component: _, ...info }) => ({
        ...acc,
        [info.name]: serializeComponentInfo(info),
      }),
      {}
    ),
    inheritedStyles: {},
    BlocksWrapper: this.blocksWrapper || DynamicDiv,
    BlocksWrapperProps: this.blocksWrapperProps || {},
    nonce: this.nonce || "",
  };

  ngOnInit() {
    this.builderContextSignal = {
      content: getContentInitialValue({
        content: this.content,
        data: this.data,
      }),
      localState: undefined,
      rootState: getRootStateInitialValue({
        content: this.content,
        data: this.data,
        locale: this.locale,
      }),
      rootSetState: this.contentSetState.bind(this),
      context: this.context || {},
      canTrack: this.canTrack,
      apiKey: this.apiKey,
      apiVersion: this.apiVersion,
      componentInfos: [
        ...getDefaultRegisteredComponents(),
        ...(this.customComponents?.filter(({ models }) => {
          if (!models?.length) return true;
          if (!this.model) return true;
          return models.includes(this.model);
        }) || []),
      ].reduce<Dictionary<ComponentInfo>>(
        (acc, { component: _, ...info }) => ({
          ...acc,
          [info.name]: serializeComponentInfo(info),
        }),
        {}
      ),
      inheritedStyles: {},
      BlocksWrapper: this.blocksWrapper || DynamicDiv,
      BlocksWrapperProps: this.blocksWrapperProps || {},
      nonce: this.nonce || "",
    };
    this.registeredComponents = [
      ...getDefaultRegisteredComponents(),
      ...(this.customComponents?.filter(({ models }) => {
        if (!models?.length) return true;
        if (!this.model) return true;
        return models.includes(this.model);
      }) || []),
    ].reduce<RegisteredComponents>(
      (acc, { component, ...info }) => ({
        ...acc,
        [info.name]: {
          component: component,
          ...serializeComponentInfo(info),
        },
      }),
      {}
    );
  }
}

// examples/react-native/src/sdk-broken/src/components/content/content.jsx
"use client";
import * as React from "react";
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
} from "react-native";
import { useState, useContext } from "react";
import { getDefaultRegisteredComponents } from "../../constants/builder-registered-components.js";
import {
  components,
  serializeComponentInfo,
} from "../../functions/register-component.js";
import Blocks from "../blocks/blocks";
import ContentStyles from "./components/styles";
import {
  getContentInitialValue,
  getContextStateInitialValue,
} from "./content.helpers.js";
import { TARGET } from "../../constants/target.js";
import { getRenderContentScriptString } from "../content-variants/helpers.js";
import EnableEditor from "./components/enable-editor";
import InlinedScript from "../inlined-script";
import { wrapComponentRef } from "./wrap-component-ref.js";
import ComponentsContext from "../../context/components.context";

function ContentComponent(props) {
  const [scriptStr, setScriptStr] = useState(() =>
    getRenderContentScriptString({
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-non-null-asserted-optional-chain
      variationId: props.content?.testVariationId,
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-non-null-asserted-optional-chain
      contentId: props.content?.id,
    })
  );

  function contentSetState(newRootState) {
    builderContextSignal.rootState = newRootState;
  }

  const [registeredComponents, setRegisteredComponents] = useState(() =>
    [
      ...getDefaultRegisteredComponents(),
      // While this `components` object is deprecated, we must maintain support for it.
      // Since users are able to override our default components, we need to make sure that we do not break such
      // existing usage.
      // This is why we spread `components` after the default Builder.io components, but before the `props.customComponents`,
      // which is the new standard way of providing custom components, and must therefore take precedence.
      ...components,
      ...(props.customComponents || []),
    ].reduce(
      (acc, { component, ...info }) => ({
        ...acc,
        [info.name]: {
          component: component,
          ...serializeComponentInfo(info),
        },
      }),
      {}
    )
  );

  const [builderContextSignal, setBuilderContextSignal] = useState(() => ({
    content: getContentInitialValue({
      content: props.content,
      data: props.data,
    }),
    localState: undefined,
    rootState: getContextStateInitialValue({
      content: props.content,
      data: props.data,
      locale: props.locale,
    }),
    rootSetState: contentSetState,
    context: props.context || {},
    apiKey: props.apiKey,
    apiVersion: props.apiVersion,
    componentInfos: [
      ...getDefaultRegisteredComponents(),
      // While this `components` object is deprecated, we must maintain support for it.
      // Since users are able to override our default components, we need to make sure that we do not break such
      // existing usage.
      // This is why we spread `components` after the default Builder.io components, but before the `props.customComponents`,
      // which is the new standard way of providing custom components, and must therefore take precedence.
      ...components,
      ...(props.customComponents || []),
    ].reduce(
      (acc, { component: _, ...info }) => ({
        ...acc,
        [info.name]: serializeComponentInfo(info),
      }),
      {}
    ),
    inheritedStyles: {},
  }));

  return (
    <ComponentsContext.Provider
      value={{
        registeredComponents: registeredComponents,
      }}
    >
      <EnableEditor
        content={props.content}
        model={props.model}
        context={props.context}
        apiKey={props.apiKey}
        canTrack={props.canTrack}
        locale={props.locale}
        includeRefs={props.includeRefs}
        enrich={props.enrich}
        classNameProp={props.classNameProp}
        showContent={props.showContent}
        builderContextSignal={builderContextSignal}
        {...{
          setBuilderContextSignal: setBuilderContextSignal,
        }}
      >
        {props.isSsrAbTest ? (
          <>
            <InlinedScript scriptStr={scriptStr} />
          </>
        ) : null}

        {TARGET !== "reactNative" ? (
          <>
            <ContentStyles
              contentId={builderContextSignal.content?.id}
              cssCode={builderContextSignal.content?.data?.cssCode}
              customFonts={builderContextSignal.content?.data?.customFonts}
            />
          </>
        ) : null}

        <Blocks
          blocks={builderContextSignal.content?.data?.blocks}
          context={builderContextSignal}
          registeredComponents={registeredComponents}
        />
      </EnableEditor>
    </ComponentsContext.Provider>
  );
}

export default ContentComponent;
