// packages/sdks/snippets/nuxt/pages/product/category/[handle].vue
<script setup lang="ts">
import { useAsyncData } from '#app'
import { fetchOneEntry } from '@builder.io/sdk-vue'

const { data: productDetails, pending } = await useAsyncData('product-details', () =>
  fetchOneEntry({
    model: 'product-details',
    apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    query: {
      'data.handle': 'jacket',
    },
  }),
)

</script>

<template>
  <div v-if="pending">Loading product details...</div>

  <div v-if="productDetails?.data">
    <h1>{{ productDetails.data.name }}</h1>
    <img :src="productDetails.data.image" :alt="productDetails.data.name" width="400" height="500" />
    <p>{{ productDetails.data.collection.value.data.copy }}</p>
    <p>Price: {{ productDetails.data.collection.value.data.price }}</p>
  </div>
</template>

// packages/sdks/snippets/react-sdk-next-14-app/app/(blueprints-product-details)/product/category/[handle]/page.tsx
import { fetchOneEntry } from '@builder.io/sdk-react';
import Image from 'next/image';

export default async function ProductDetailsPage({
  params,
}: {
  params: { handle: string };
}) {
  const productDetails = await fetchOneEntry({
    model: 'product-details',
    apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    query: {
      'data.handle': params.handle,
    },
  });

  return (
    <>
      {productDetails && (
        <div className="product-details">
          <h1>{productDetails.data?.name}</h1>
          <Image
            src={`${productDetails.data?.image}`}
            alt={productDetails.data?.name}
            width={400}
            height={500}
            priority={true}
          />
          <p>{productDetails.data?.collection.value.data.copy}</p>
          <p>Price: {productDetails.data?.collection.value.data.price}</p>
        </div>
      )}
    </>
  );
}
