// examples/svelte/sveltekit/src/lib/DynamicallyRenderBuilderPage.svelte
<script context="module" lang="ts">
  export const prerender = true;
</script>

<script lang="ts">
  import { page } from '$app/stores';

  import Counter from '$lib/Counter.svelte';

  import {
    getContent,
    getBuilderSearchParams,
    convertSearchParamsToQueryObject,
    isEditing,
    RenderContent
  } from '@builder.io/sdk-svelte';

  const CUSTOM_COMPONENTS = [
    {
      component: Counter,
      name: 'Counter',
      inputs: [
        {
          name: 'name',
          type: 'string',
          defaultValue: 'hello'
        },
        {
          name: 'count',
          type: 'number',
          defaultValue: 0
        }
      ]
    }
  ];
  // TODO: enter your public API key
  const BUILDER_PUBLIC_API_KEY = 'f1a790f8c3204b3b8c5c1795aeac4660'; // ggignore

  let content = undefined;
  let canShowContent = false;
  const fetch = async () => {
    content = await getContent({
      model: 'page',
      apiKey: BUILDER_PUBLIC_API_KEY,
      options: getBuilderSearchParams(convertSearchParamsToQueryObject($page.url.searchParams)),
      userAttributes: {
        urlPath: $page.url.pathname
      }
    });
    canShowContent = content || isEditing();
  };

  fetch();
</script>

<div>Hello world from your SvelteKit project. Below is Builder Content:</div>

{#if canShowContent}
  <div>page: {(content && content.data && content.data.title) || 'Unpublished'}</div>
  <RenderContent
    model="page"
    {content}
    apiKey={BUILDER_PUBLIC_API_KEY}
    customComponents={CUSTOM_COMPONENTS}
  />
{/if}

// examples/vue/vue-2/src/components/Builder/DynamicallyRenderBuilderPage.vue
<template>
  <div id="home">
    <div>Hello world from your Vue project. Below is Builder Content:</div>

    <div v-if="canShowContent">
      <div>
        page:
        {{ (content && content.data && content.data.title) || 'Unpublished' }}
      </div>
      <builder-render-content
        model="page"
        :content="content"
        :api-key="apiKey"
        :customComponents="getRegisteredComponents()"
      />
    </div>
  </div>
</template>
<script>
import Vue from 'vue';

import { REGISTERED_COMPONENTS } from './init-builder.ts';
import {
  RenderContent,
  getContent,
  getBuilderSearchParams,
  convertSearchParamsToQueryObject,
  isEditing,
  isPreviewing,
} from '@builder.io/sdk-vue/vue2';

// TODO: enter your public API key
const BUILDER_PUBLIC_API_KEY = 'f1a790f8c3204b3b8c5c1795aeac4660'; // ggignore

export default Vue.extend({
  name: 'DynamicallyRenderBuilderPage',
  components: {
    'builder-render-content': RenderContent,
  },
  data: () => ({
    canShowContent: false,
    content: null,
    apiKey: BUILDER_PUBLIC_API_KEY,
  }),
  methods: {
    getRegisteredComponents() {
      return REGISTERED_COMPONENTS;
    },
  },
  mounted() {
    getContent({
      model: 'page',
      apiKey: BUILDER_PUBLIC_API_KEY,
      options: getBuilderSearchParams(
        convertSearchParamsToQueryObject(new URLSearchParams(window.location.search))
      ),
      userAttributes: {
        urlPath: window.location.pathname,
      },
    }).then(res => {
      this.content = res;
      this.canShowContent = this.content || isEditing() || isPreviewing();
    });
  },
});
</script>

<style>
#home {
  box-sizing: border-box;
  padding: 0 var(--spacer-sm);
  max-width: 1240px;
  padding: 0;
  margin: 0 auto;
}
</style>
