// packages/sdks/snippets/angular-16/src/app/live-preview/live-preview.component.ts
import { CommonModule } from '@angular/common';
import type { OnDestroy, OnInit } from '@angular/core';
import { Component } from '@angular/core';
import type { BuilderContent } from '@builder.io/sdk-angular';
import { subscribeToEditor } from '@builder.io/sdk-angular';

@Component({
  standalone: true,
  selector: 'app-live-preview',
  imports: [CommonModule],
  template: `
    <div *ngIf="content" class="blog-data-preview">
      <div>Blog Title: {{ content.data?.title }}</div>
      <div>Authored by: {{ content.data?.['author'] }}</div>
      <div>Handle: {{ content.data?.['handle'] }}</div>
    </div>
  `,
})
export class LivePreviewComponent implements OnInit, OnDestroy {
  content: BuilderContent | null = null;

  private unsubscribeFn: () => void = () => {};

  ngOnInit(): void {
    this.unsubscribeFn = subscribeToEditor({
      model: 'blog-data',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      callback: (updatedContent) => {
        this.content = updatedContent;
      },
    });
  }

  ngOnDestroy(): void {
    if (this.unsubscribeFn) {
      this.unsubscribeFn();
    }
  }
}

// packages/sdks/snippets/sveltekit/src/routes/live-preview/+page.svelte
<script lang="ts">
  import type { BuilderContent } from '@builder.io/sdk-svelte';
  import { onMount, onDestroy } from 'svelte';
  import { subscribeToEditor } from '@builder.io/sdk-svelte';

  export let data: {
    content: BuilderContent | null;
  };

  let content: BuilderContent | null = data.content;
  let isLoading = !content;

  let unsubscribe: (() => void) | null = null;

  onMount(() => {
    unsubscribe = subscribeToEditor({
      model: 'blog-data',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      callback(updatedContent) {
        content = updatedContent;
        isLoading = false;
      },
    });

    return () => {
      if (unsubscribe) unsubscribe();
    };
  });

  onDestroy(() => {
    if (unsubscribe) unsubscribe();
  });
</script>

{#if isLoading && !content}
  <div>Loading...</div>
{/if}

{#if content}
  <div class="blog-data-preview">
    <div>Blog Title: {content.data?.title}</div>
    <div>Authored by: {content.data?.author}</div>
    <div>Handle: {content.data?.handle}</div>
  </div>
{/if}
