// packages/sdks/snippets/nuxt/pages/editable-region.vue
<template>
    <div>
      <div v-if="pending">Loading...</div>
      <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
      <Content
        v-else
        :content="content"
        model="editable-regions"
        apiKey="ee9f13b4981e489a9a1209887695ef2b"
        :customComponents="[CustomColumnsInfo]"
      />
    </div>
  </template>
  
  <script setup lang="ts">
  import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-vue';
  import CustomColumnsInfo from '../components/CustomColumnsInfo';

  const route = useRoute();
  const model = 'editable-regions';
  const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const { data: content, pending } = await useAsyncData(
  `builder-${model}-${route.path}`,
  () => fetchOneEntry({
    model,
    apiKey,
    userAttributes: {urlPath: route.path},
    })
  );

  </script>

// packages/sdks/snippets/sveltekit/src/routes/editable-region/+page.svelte
<script lang="ts">
  import { Content, isPreviewing } from '@builder.io/sdk-svelte';
  import type { PageData } from './$types';
  import { CustomColumnsInfo } from './CustomColumnsInfo';

  export let data: PageData;
</script>

{#if !data.data && !isPreviewing()}
  <div>404 - Not Found</div>
{:else}
  <Content
    content={data.data}
    apiKey="ee9f13b4981e489a9a1209887695ef2b"
    model="editable-regions"
    customComponents={[CustomColumnsInfo]}
  />
{/if}
