// packages/sdks/snippets/vue/src/views/blueprints/ProductEditorial.vue
<!-- src/views/ProductEditorial.vue -->
<template>
  <div v-if="!product && !editorial && !isPreviewing()">404</div>
  <div v-else>
    <ProductHeader />
    <ProductInfo :product="product" />
    <Content :model="modelName" :content="editorial" :apiKey="apiKey" />
    <ProductFooter />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type BuilderContent,
} from '@builder.io/sdk-vue';
import ProductHeader from '@/components/product-editorial/ProductHeader.vue';
import ProductFooter from '@/components/product-editorial/ProductFooter.vue';
import ProductInfo from '@/components/product-editorial/ProductInfo.vue';
import { useRoute } from 'vue-router';

const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
const modelName = 'product-editorial';

const product = ref(null);
const editorial = ref<BuilderContent | null>(null);
const { params } = useRoute();

onMounted(() => {
  fetch(`https://fakestoreapi.com/products/${params.id}`)
    .then((res) => res.json())
    .then((data) => {
      product.value = data;
    });

  fetchOneEntry({
    model: modelName,
    apiKey: apiKey,
    userAttributes: { urlPath: window.location.pathname },
  }).then((data) => {
    editorial.value = data;
  });
});
</script>

// packages/sdks/snippets/svelte/src/components/blueprints/product-editorial/ProductEditorial.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    fetchOneEntry,
    Content,
    type BuilderContent,
    isPreviewing,
  } from '@builder.io/sdk-svelte';
  import ProductHeader from './ProductHeader.svelte';
  import ProductFooter from './ProductFooter.svelte';
  import ProductInfo from './ProductInfo.svelte';

  const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
  const modelName = 'product-editorial';
  export let handle: string;
  let product: any = null;
  let editorial: BuilderContent | null = null;

  onMount(() => {
    fetch(`https://fakestoreapi.com/products/${handle}`)
      .then((res) => res.json())
      .then((data) => {
        product = data;
      });

    fetchOneEntry({
      model: modelName,
      apiKey: API_KEY,
      userAttributes: { urlPath: window.location.pathname },
    }).then((data) => {
      editorial = data;
    });
  });
</script>

{#if !product && !editorial && isPreviewing()}
  <p>404</p>
{:else}
  <ProductHeader />
  <ProductInfo {product} />
  <Content model={modelName} content={editorial} apiKey={API_KEY} />
  <ProductFooter />
{/if}
