// packages/sdks/snippets/react/src/components/CustomTabs.tsx
import {
  Blocks,
  BuilderBlock,
  RegisteredComponent,
} from '@builder.io/sdk-react';
import { useState } from 'react';

interface TabProps {
  tabList?: { tabName: string; blocks: BuilderBlock[] }[];
  builderBlock: BuilderBlock;
}

export const CustomTabs = ({ tabList, builderBlock }: TabProps) => {
  const [activeTab, setActiveTab] = useState(0);

  if (!tabList?.length) return null;

  return (
    <>
      <div className="tab-buttons">
        {tabList.map((tab, index) => (
          <button
            key={index}
            className={`tab-button ${activeTab === index ? 'active' : ''}`}
            onClick={() => setActiveTab(index)}
          >
            {tab.tabName}
          </button>
        ))}
      </div>

      <div className="tab-content">
        <Blocks
          parent={builderBlock?.id}
          path={`tabList[${activeTab}].blocks`}
          blocks={tabList[activeTab].blocks}
        />
      </div>
    </>
  );
};

export const customTabsInfo: RegisteredComponent = {
  component: CustomTabs,
  name: 'TabFields',
  shouldReceiveBuilderProps: {
    builderBlock: true,
    builderComponents: true,
    builderContext: true,
  },
  inputs: [
    {
      name: 'tabList',
      type: 'list',
      subFields: [
        {
          name: 'tabName',
          type: 'string',
        },
        {
          name: 'blocks',
          type: 'uiBlocks',
          hideFromUI: true,
          defaultValue: [],
        },
      ],
    },
  ],
};

// packages/sdks/snippets/angular-17-ssr/src/app/advanced-child/custom-tabs/custom-tabs.component.ts
import { Component, Input } from '@angular/core';
import type {
  BuilderBlock,
  BuilderContextInterface,
  RegisteredComponent,
  RegisteredComponents,
} from '@builder.io/sdk-angular';
import { Blocks } from '@builder.io/sdk-angular';

@Component({
  selector: 'app-custom-tabs',
  standalone: true,
  imports: [Blocks],
  template: `
    @if (tabList.length) {
      @for (tab of tabList; track $index) {
        <button
          [class.active]="activeTab === $index"
          (click)="activeTab = $index"
        >
          {{ tab.tabName }}
        </button>
      }

      <blocks
        [blocks]="tabList[activeTab].blocks"
        [path]="'tabList.' + activeTab + '.blocks'"
        [parent]="builderBlock.id"
        [context]="builderContext"
        [registeredComponents]="builderComponents"
      />
    }
  `,
})
export class CustomTabsComponent {
  @Input() builderBlock!: BuilderBlock;
  @Input() tabList: { tabName: string; blocks: BuilderBlock[] }[] = [];
  @Input() builderComponents: RegisteredComponents = {};
  @Input() builderContext!: BuilderContextInterface;

  activeTab = 0;
}

export const customTabsInfo: RegisteredComponent = {
  component: CustomTabsComponent,
  name: 'TabFields',
  inputs: [
    {
      name: 'tabList',
      type: 'list',
      subFields: [
        {
          name: 'tabName',
          type: 'string',
        },
        {
          name: 'blocks',
          type: 'uiBlocks',
          defaultValue: [],
        },
      ],
    },
  ],
  shouldReceiveBuilderProps: {
    builderBlock: true,
    builderComponents: true,
    builderContext: true,
  },
};
