// examples/next-app-dir/src/sdk-src/blocks/embed/embed.tsx
'use client'
import * as React from 'react'
import { useState, useRef, useEffect } from 'react'

export interface EmbedProps {
  content: string
}

import { isJsScript } from './helpers'

function Embed(props: EmbedProps) {
  const elem = useRef<HTMLDivElement>(null)
  const [scriptsInserted, setScriptsInserted] = useState(() => [])

  const [scriptsRun, setScriptsRun] = useState(() => [])

  const [ranInitFn, setRanInitFn] = useState(() => false)

  function findAndRunScripts() {
    if (!elem.current || !elem.current.getElementsByTagName) return
    const scripts = elem.current.getElementsByTagName('script')
    for (let i = 0; i < scripts.length; i++) {
      const script = scripts[i]
      if (script.src && !scriptsInserted.includes(script.src)) {
        scriptsInserted.push(script.src)
        const newScript = document.createElement('script')
        newScript.async = true
        newScript.src = script.src
        document.head.appendChild(newScript)
      } else if (isJsScript(script) && !scriptsRun.includes(script.innerText)) {
        try {
          scriptsRun.push(script.innerText)
          new Function(script.innerText)()
        } catch (error) {
          console.warn('`Embed`: Error running script:', error)
        }
      }
    }
  }

  useEffect(() => {
    if (elem.current && !ranInitFn) {
      setRanInitFn(true)
      findAndRunScripts()
    }
  }, [elem.current, ranInitFn])

  return (
    <div
      className="builder-embed"
      ref={elem}
      dangerouslySetInnerHTML={{ __html: props.content }}
    />
  )
}

export default Embed

// packages/sdks/output/angular/src-copy-fast-diff/blocks/embed/embed.ts
import { Component, ViewChild, ElementRef, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

export interface EmbedProps {
  content: string;
}

import { isJsScript } from "./helpers";

@Component({
  selector: "builder-embed, BuilderEmbed",
  template: `
    <div class="builder-embed" #elem [innerHTML]="content"></div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class BuilderEmbed {
  @Input() content!: EmbedProps["content"];

  @ViewChild("elem") elem!: ElementRef;

  scriptsInserted = [];
  scriptsRun = [];
  ranInitFn = false;
  findAndRunScripts() {
    if (
      !this.elem.nativeElement ||
      !this.elem.nativeElement.getElementsByTagName
    )
      return;
    const scripts = this.elem.nativeElement.getElementsByTagName("script");
    for (let i = 0; i < scripts.length; i++) {
      const script = scripts[i];
      if (script.src && !this.scriptsInserted.includes(script.src)) {
        this.scriptsInserted.push(script.src);
        const newScript = document.createElement("script");
        newScript.async = true;
        newScript.src = script.src;
        document.head.appendChild(newScript);
      } else if (
        isJsScript(script) &&
        !this.scriptsRun.includes(script.innerText)
      ) {
        try {
          this.scriptsRun.push(script.innerText);
          new Function(script.innerText)();
        } catch (error) {
          console.warn("`Embed`: Error running script:", error);
        }
      }
    }
  }

  ngOnChanges() {
    if (typeof window !== "undefined") {
      if (this.elem.nativeElement && !this.ranInitFn) {
        this.ranInitFn = true;
        this.findAndRunScripts();
      }
    }
  }
}
