// packages/sdks/snippets/gen1-next-14/pages/announcements/[...index].tsx
/**
 * https://www.builder.io/c/docs/integrate-section-building
 * https://www.builder.io/c/blueprints/announcement-bar
 * snippets/gen1-nextjs/pages/announcements/[...index].tsx
 */
import { BuilderComponent, builder } from '@builder.io/react';
import type { BuilderContent } from '@builder.io/sdk';
import type { GetStaticProps } from 'next';
import React from 'react';

builder.init('ee9f13b4981e489a9a1209887695ef2b');

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const urlPath =
    '/announcements/' +
    (Array.isArray(params?.index)
      ? params.index.join('/')
      : params?.index || '');

  const announcementBar = await builder
    .get('announcement-bar', {
      userAttributes: {
        urlPath,
      },
    })
    .promise();

  return {
    props: {
      announcementBar: announcementBar || null,
    },
  };
};

export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: 'blocking',
  };
};

export default function Page({
  announcementBar,
}: {
  announcementBar: BuilderContent | null;
}) {
  return (
    <>
      {announcementBar && (
        <BuilderComponent model="announcement-bar" content={announcementBar} />
      )}
      {/* content coming from your app (or also Builder) */}
      <div>The rest of your page goes here</div>
    </>
  );
}

// packages/sdks/snippets/qwik-city/src/routes/announcements/[...index]/index.tsx
/**
 * https://www.builder.io/c/docs/integrate-section-building
 * https://www.builder.io/c/blueprints/announcement-bar
 * src/routes/announcements/[...index]/index.tsx
 */
import { component$ } from '@builder.io/qwik';
import { routeLoader$ } from '@builder.io/qwik-city';
import {
  Content,
  fetchOneEntry,
} from '@builder.io/sdk-qwik';

export const BUILDER_PUBLIC_API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
export const BUILDER_MODEL = 'announcement-bar';

export const useBuilderContent = routeLoader$(async ({ url }) => {
  const announcementBar = await fetchOneEntry({
    model: BUILDER_MODEL,
    apiKey: BUILDER_PUBLIC_API_KEY,

    userAttributes: {
      urlPath: url.pathname,
    },
  });

  return announcementBar;
});

export default component$(() => {
  const announcement = useBuilderContent();

  return (
    <>
      {announcement.value && (
        <Content
          model={BUILDER_MODEL}
          content={announcement.value}
          apiKey={BUILDER_PUBLIC_API_KEY}
        />
      )}

      {/* Your content coming from your app (or also Builder) */}
      <div>The rest of your page goes here</div>
    </>
  );
});
