// packages/sdks/output/vue/nuxt2/src/blocks/fragment.vue
<template>
  <span><slot></slot></span>
</template>
<script>
import { registerComponent } from '@builder.io/sdk-vue';

export default registerComponent(
  {
    name: 'builder-fragment-component',

    props: [],
  },
  {
    name: 'Fragment',
    static: true,
    hidden: true,
    builtIn: true,
    canHaveChildren: true,
    noWrap: true,
  }
);
</script>

// packages/react/src/blocks/Fragment.tsx
import React from 'react';
import { BuilderElement } from '@builder.io/sdk';
import { withBuilder } from '../functions/with-builder';
import { BuilderBlock as BuilderBlockComponent } from '../components/builder-block.component';

export interface FragmentProps {
  builderBlock?: BuilderElement;
}

class FragmentComponent extends React.Component<FragmentProps> {
  render() {
    return (
      this.props.builderBlock &&
      this.props.builderBlock.children &&
      this.props.builderBlock.children.map((block, index) => (
        <BuilderBlockComponent block={block} key={block.id} index={index} />
      ))
    );
  }
}

export const Fragment = withBuilder(FragmentComponent, {
  name: 'Core:Fragment',
  canHaveChildren: true,
  noWrap: true,
  static: true,
  hideFromInsertMenu: true,
});
