// packages/sdks/output/solid/src/components/render-blocks.lite.tsx
import { Show, For } from "solid-js";

import { createMutable } from "solid-js/store";
import { css } from "solid-styled-components";

import { isEditing } from "../functions/is-editing";
import RenderBlock from "./render-block.lite";

export default function RenderBlocks(props) {
  const state = createMutable({
    get className() {
      return "builder-blocks" + (!props.blocks?.length ? " no-blocks" : "");
    },
    onClick() {
      if (isEditing() && !props.blocks?.length) {
        window.parent?.postMessage(
          {
            type: "builder.clickEmptyBlocks",
            data: {
              parentElementId: props.parent,
              dataPath: props.path,
            },
          },
          "*"
        );
      }
    },
    onMouseEnter() {
      if (isEditing() && !props.blocks?.length) {
        window.parent?.postMessage(
          {
            type: "builder.hoverEmptyBlocks",
            data: {
              parentElementId: props.parent,
              dataPath: props.path,
            },
          },
          "*"
        );
      }
    },
  });

  return (
    <div
      class={
        state.className +
        " " +
        css({
          display: "flex",
          flexDirection: "column",
          alignItems: "stretch",
        })
      }
      builder-path={props.path}
      builder-parent-id={props.parent}
      dataSet={{
        class: state.className,
      }}
      onClick={(event) => state.onClick()}
      onMouseEnter={(event) => state.onMouseEnter()}
    >
      <Show when={props.blocks}>
        <For each={props.blocks}>
          {(block, index) => (
            <RenderBlock key={block.id} block={block}></RenderBlock>
          )}
        </For>
      </Show>
    </div>
  );
}

// packages/sdks/output/react-native/src/components/render-blocks.lite.tsx
import * as React from 'react';
import { View, StyleSheet, Image, Text } from 'react-native';
import { isEditing } from '../functions/is-editing';
import RenderBlock from './render-block.lite';

export default function RenderBlocks(props) {
  function className() {
    return 'builder-blocks' + (!props.blocks?.length ? ' no-blocks' : '');
  }

  function onClick() {
    if (isEditing() && !props.blocks?.length) {
      window.parent?.postMessage(
        {
          type: 'builder.clickEmptyBlocks',
          data: {
            parentElementId: props.parent,
            dataPath: props.path,
          },
        },
        '*'
      );
    }
  }

  function onMouseEnter() {
    if (isEditing() && !props.blocks?.length) {
      window.parent?.postMessage(
        {
          type: 'builder.hoverEmptyBlocks',
          data: {
            parentElementId: props.parent,
            dataPath: props.path,
          },
        },
        '*'
      );
    }
  }

  return (
    <View
      builder-path={props.path}
      builder-parent-id={props.parent}
      dataSet={{
        class: className(),
      }}
      onClick={(event) => onClick()}
      onMouseEnter={(event) => onMouseEnter()}
      style={styles.view1}
    >
      {props.blocks ? (
        <>
          {props.blocks?.map((block, index) => (
            <RenderBlock key={block.id} block={block} />
          ))}
        </>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  view1: { display: 'flex', flexDirection: 'column', alignItems: 'stretch' },
});
