// packages/sdks/output/solid/src/components/render-inlined-styles.lite.tsx
import { Show } from "solid-js";
import { Dynamic } from "solid-js/web";
import { createMutable } from "solid-js/store";

import { TARGET } from "../constants/target.js";

function RenderInlinedStyles(props) {
  const state = createMutable({
    get injectedStyleScript() {
      return `<${state.tagName}>${props.styles}</${state.tagName}>`;
    },
    get tagName() {
      // NOTE: we have to obfusctate the name of the tag due to a limitation in the svelte-preprocessor plugin.
      // https://github.com/sveltejs/vite-plugin-svelte/issues/315#issuecomment-1109000027
      return "sty" + "le";
    },
  });

  return (
    <Show when={TARGET === "svelte"}>
      <div innerHTML={state.injectedStyleScript}></div>
    </Show>
  );
}

export default RenderInlinedStyles;

// packages/sdks/output/react-native/src/components/render-inlined-styles.lite.tsx
import * as React from "react";
import { View, StyleSheet, Image, Text } from "react-native";
import { TARGET } from "../constants/target";

export default function RenderInlinedStyles(props) {
  function injectedStyleScript() {
    return `<${tagName()}>${props.styles}</${tagName()}>`;
  }

  function tagName() {
    // NOTE: we have to obfusctate the name of the tag due to a limitation in the svelte-preprocessor plugin.
    // https://github.com/sveltejs/vite-plugin-svelte/issues/315#issuecomment-1109000027
    return "sty" + "le";
  }

  const TagNameRef = tagName();

  return (
    <>
      {TARGET === "svelte" ? (
        <>
          <></>
        </>
      ) : (
        <TagNameRef>
          <Text>{props.styles}</Text>
        </TagNameRef>
      )}
    </>
  );
}
