// packages/sdks/output/svelte/src/blocks/select.svelte
<script>
  
  
  
  
import  {  isEditing  }  from '../functions/is-editing';




  
  export let attributes;
export let value;
export let defaultValue;
export let name;
export let options;

  
  

  

  

  

  
</script>

<select {...attributes} value={value}  key={isEditing() && defaultValue ? defaultValue : 'default-key'}  defaultValue={defaultValue}  name={name} >
  
{#each options as option, index }<option  value={option.value} >{option.name || option.value}</option>{/each}

</select>

// packages/sdks/output/vue/nuxt2/src/blocks/select/select.vue
<template>
  <select
    v-bind="attributes"
    :value="value"
    :key="isEditing() && defaultValue ? defaultValue : 'default-key'"
    :defaultValue="defaultValue"
    :name="name"
  >
    <option
      v-for="(option, index) in options"
      :value="option.value"
      :key="index"
    >
      {{ option.name || option.value }}
    </option>
  </select>
</template>
<script>
import { isEditing } from "../../functions/is-editing.js";

export default {
  name: "builder-select-component",

  props: ["attributes", "value", "defaultValue", "name", "options"],

  data: () => ({ isEditing }),
};
</script>
