// examples/react-v2/src/sdk-src/blocks/text/text.tsx
import * as React from "react";
import type { TextProps } from "./text.types.js";

function Text(props: TextProps) {
  return (
    <div
      className="builder-text"
      dangerouslySetInnerHTML={{ __html: props.text?.toString() || "" }}
      style={{
        outline: "none",
      }}
    />
  );
}

export default Text;

// examples/vue/nuxt-3/sdk-src/blocks/text/text.vue
<template>
  <span
    class="builder-text"
    v-html="text"
    :style="{
      outline: 'none',
    }"
  ></span>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export interface TextProps {
  text: string;
}

export default defineComponent({
  name: "builder-text",

  props: ["text"],
});
</script>
