// packages/sdks/output/solid/src/blocks/fragment.jsx
function FragmentComponent(props) {
  return <span>{props.children}</span>;
}

export default FragmentComponent;import { registerComponent } from '../functions/register-component';
registerComponent(FragmentComponent, {name:'Fragment',static:true,hidden:true,builtIn:true,canHaveChildren:true,noWrap:true});

// packages/sdks/output/vue/nuxt2/src/blocks/fragment.vue
<template>
  <span><slot></slot></span>
</template>
<script>
import { registerComponent } from '../functions/register-component';

export default registerComponent(
  {
    name: 'builder-fragment-component',

    props: [],
  },
  {
    name: 'Fragment',
    static: true,
    hidden: true,
    builtIn: true,
    canHaveChildren: true,
    noWrap: true,
  }
);
</script>
