// packages/react/src/blocks/raw/RawText.tsx
import * as React from 'react';
import { BuilderElement, Builder } from '@builder.io/sdk';

export interface RawTextProps {
  attributes?: any;
  text?: string;
  builderBlock?: BuilderElement;
}

export const RawText = (props: RawTextProps) => {
  const attributes = props.attributes || {};
  return (
    <span
      className={attributes?.class || attributes?.className}
      dangerouslySetInnerHTML={{ __html: props.text || '' }}
    />
  );
};

Builder.registerComponent(RawText, {
  name: 'Builder:RawText',
  hideFromInsertMenu: true,
  inputs: [
    {
      name: 'text',
      bubble: true,
      type: 'longText',
      required: true,
    },
  ],
});

// packages/sdks/output/vue/nuxt2/src/blocks/raw-text.vue
<template>
  <span
    :class="_classStringToObject((this.attributes && this.attributes.class) || (this.attributes && this.attributes.className))"
    v-html="text || ''"
  ></span>
</template>
<script>
import { registerComponent } from "@builder.io/sdk-vue";

export default registerComponent(
  {
    name: "builder-raw-text",

    props: ["attributes", "text"],

    methods: {
      _classStringToObject(str) {
        const obj = {};
        if (typeof str !== "string") {
          return obj;
        }
        const classNames = str.trim().split(/\s+/);
        for (const name of classNames) {
          obj[name] = true;
        }
        return obj;
      },
    },
  },
  {
    name: "Builder:RawText",
    hideFromInsertMenu: true,
    builtIn: true,
    inputs: [{ name: "text", bubble: true, type: "longText", required: true }],
  }
);
</script>
