// packages/react-native/src/blocks/Section.tsx
import React from 'react'
import { BuilderElement } from '@builder.io/sdk'
import { BuilderBlock } from '../decorators/builder-block.decorator'
import { BuilderBlock as BuilderBlockComponent } from '../components/builder-block.component'
import { View } from 'react-native';

interface SectionProps {
  builderBlock?: BuilderElement
  verticalAlignContent?: string
  maxWidth?: number
}

// TODO: acceptsChildren option?
@BuilderBlock({
  name: 'Core:Section',
  image:
    'https://cdn.builder.io/api/v1/image/assets%2FIsxPKMo2gPRRKeakUztj1D6uqed2%2F682efef23ace49afac61748dd305c70a',
  inputs: [
    {
      name: 'maxWidth',
      type: 'number',
      defaultValue: 1200
    }
  ],
  defaultStyles: {
    paddingLeft: '20px',
    paddingRight: '20px',
    paddingTop: '50px',
    paddingBottom: '50px',
    marginTop: '0px',
    width: '100vw',
    marginLeft: 'calc(50% - 50vw)'
  },
  canHaveChildren: true,

  // TODO: defaults that deep merge and can be anyting - responsive styles, etc
  defaultChildren: [
    {
      '@type': '@builder.io/sdk:Element',
      responsiveStyles: {
        large: {
          textAlign: 'center'
        }
      },
      component: {
        name: 'Text',
        options: {
          text:
            "<p><b>I am a section! My content keeps from getting too wide, so that it's easy to read even on big screens.</b></p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>"
        }
      }
    }
  ]
  // TODO
  // defaultChildren: ..

  // Share these hooks across the projects
  // hooks: {
  //   'BlocksOverlay::debounceNextTickUpdateStyles#updateStyles': () => convert margin selectors to paddings of table
  //   '@builder.io/app:Style.foo': () => { /* ... */ } // maybe optionally async
  // }
})
export class Section extends React.Component<SectionProps> {
  render() {
    return (
      <View
        style={{
          // margin: 'auto',
          // TODO: maybe remove height: '100%'
          height: '100%',
          width: '100%',
          alignSelf: 'stretch',
          flexGrow: 1,
          // boxSizing: 'border-box',
          maxWidth: this.props.maxWidth,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'stretch',
          marginLeft: 'auto',
          marginRight: 'auto'
        }}
      >
        {/* TODO: maybe builder <BuilderBlocks? */}
        {this.props.builderBlock &&
          this.props.builderBlock.children &&
          this.props.builderBlock.children.map((block, index) => (
            <BuilderBlockComponent key={block.id} block={block} />
          ))}
        {/* <BuilderBlocks blocks={this.builderBlock.children} dataPath="children" emailMode /> */}
      </View>
    )
  }
}

// packages/sdks/output/vue/nuxt2/src/blocks/section.vue
<template>
  <section
    v-bind="attributes"
    :style="
      maxWidth && typeof maxWidth === 'number'
        ? {
            maxWidth: maxWidth,
          }
        : undefined
    "
  >
    <slot></slot>
  </section>
</template>
<script>
import { registerComponent } from '@builder.io/sdk-vue';

export default registerComponent(
  {
    name: 'builder-section-component',

    props: ['attributes', 'maxWidth'],
  },
  {
    name: 'Core:Section',
    static: true,
    builtIn: true,
    image:
      'https://cdn.builder.io/api/v1/image/assets%2FIsxPKMo2gPRRKeakUztj1D6uqed2%2F682efef23ace49afac61748dd305c70a',
    inputs: [
      { name: 'maxWidth', type: 'number', defaultValue: 1200 },
      {
        name: 'lazyLoad',
        type: 'boolean',
        defaultValue: false,
        advanced: true,
        description: 'Only render this section when in view',
      },
    ],
    defaultStyles: {
      paddingLeft: '20px',
      paddingRight: '20px',
      paddingTop: '50px',
      paddingBottom: '50px',
      marginTop: '0px',
      width: '100vw',
      marginLeft: 'calc(50% - 50vw)',
    },
    canHaveChildren: true,
    defaultChildren: [
      {
        '@type': '@builder.io/sdk:Element',
        responsiveStyles: { large: { textAlign: 'center' } },
        component: {
          name: 'Text',
          options: {
            text: "<p><b>I am a section! My content keeps from getting too wide, so that it's easy to read even on big screens.</b></p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>",
          },
        },
      },
    ],
  }
);
</script>
