// packages/sdks/output/svelte/src/blocks/textarea.svelte
<script>
  
  
  
  



  

  
  export let attributes;
export let placeholder;
export let name;
export let value;
export let defaultValue;
  
  
  

  
  
  

  

  

  
</script>

<textarea {...attributes} placeholder={placeholder}  name={name}  value={value}  defaultValue={defaultValue} ></textarea>

// packages/sdks/output/vue/nuxt2/src/blocks/textarea.vue
<template>
  <textarea
    v-bind="attributes"
    :placeholder="placeholder"
    :name="name"
    :value="value"
    :defaultValue="defaultValue"
  ></textarea>
</template>
<script>
export default {
  name: "builder-textarea",

  props: ["attributes", "placeholder", "name", "value", "defaultValue"],
};
</script>
