// packages/sdks/output/svelte/src/blocks/select.svelte
<script>
  
  
  
  
import  {  isEditing  }  from '../functions/is-editing';




  
  export let attributes;
export let value;
export let defaultValue;
export let name;
export let options;

  
  

  

  

  

  
</script>

<select {...attributes} value={value}  key={isEditing() && defaultValue ? defaultValue : 'default-key'}  defaultValue={defaultValue}  name={name} >
  
{#each options as option, index }<option  value={option.value} >{option.name || option.value}</option>{/each}

</select>

// packages/sdks/output/solid/src/blocks/select/select.jsx
import { For } from "solid-js";
import { isEditing } from "../../functions/is-editing.js";

function SelectComponent(props) {
  return <select {...props.attributes} value={props.value} key={isEditing() && props.defaultValue ? props.defaultValue : "default-key"} defaultValue={props.defaultValue} name={props.name}>
      <For each={props.options}>
        {(option, _index) => {
        const index = _index();

        return <option value={option.value}>{option.name || option.value}</option>;
      }}
      </For>
    </select>;
}

export default SelectComponent;
