// packages/sdks/output/angular/src/components/content/components/enable-editor.ts
import {
  Component,
  ViewChild,
  ElementRef,
  Input,
  ViewContainerRef,
  TemplateRef,
} from "@angular/core";
import { CommonModule } from "@angular/common";

type BuilderEditorProps = Omit<
  ContentProps,
  | "customComponents"
  | "apiVersion"
  | "isSsrAbTest"
  | "blocksWrapper"
  | "blocksWrapperProps"
  | "isNestedRender"
  | "linkComponent"
> & {
  builderContextSignal: BuilderContextInterface;
  setBuilderContextSignal?: (signal: any) => any;
  children?: any;
};

import builderContext from "../../../context/builder.context";
import type { BuilderContextInterface } from "../../../context/types";
import { evaluate } from "../../../functions/evaluate/index";
import { fastClone } from "../../../functions/fast-clone";
import { fetchOneEntry } from "../../../functions/get-content/index";
import { fetch } from "../../../functions/get-fetch";
import { isBrowser } from "../../../functions/is-browser";
import { isEditing } from "../../../functions/is-editing";
import { isPreviewing } from "../../../functions/is-previewing";
import { createRegisterComponentMessage } from "../../../functions/register-component";
import { _track } from "../../../functions/track/index";
import { getInteractionPropertiesForEvent } from "../../../functions/track/interaction";
import { getDefaultCanTrack } from "../../../helpers/canTrack";
import { logger } from "../../../helpers/logger";
import { postPreviewContent } from "../../../helpers/preview-lru-cache/set";
import { createEditorListener } from "../../../helpers/subscribe-to-editor";
import {
  registerInsertMenu,
  setupBrowserForEditing,
} from "../../../scripts/init-editing";
import type { BuilderContent } from "../../../types/builder-content";
import type { ComponentInfo } from "../../../types/components";
import type { Dictionary } from "../../../types/typescript";
import { triggerAnimation } from "../../block/animator";
import DynamicDiv from "../../dynamic-div";
import type {
  BuilderComponentStateChange,
  ContentProps,
} from "../content.types";
import { getWrapperClassName } from "./styles.helpers";

@Component({
  selector: "enable-editor, EnableEditor",
  template: `
    <ng-template #contentwrapperTemplate><ng-content></ng-content></ng-template>
    <ng-container *ngIf="builderContextSignal.content">
      <ng-container
        *ngComponentOutlet="
              ContentWrapper;
              inputs: mergedInputs_5xe0fc;
              content: myContent;
              "
      ></ng-container>
    </ng-container>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class EnableEditor {
  builderContext = builderContext;

  @Input() locale!: BuilderEditorProps["locale"];
  @Input() enrich!: BuilderEditorProps["enrich"];
  @Input() trustedHosts!: BuilderEditorProps["trustedHosts"];
  @Input() builderContextSignal!: BuilderEditorProps["builderContextSignal"];
  @Input() canTrack!: BuilderEditorProps["canTrack"];
  @Input() apiKey!: BuilderEditorProps["apiKey"];
  @Input() model!: BuilderEditorProps["model"];
  @Input() content!: BuilderEditorProps["content"];
  @Input() data!: BuilderEditorProps["data"];
  @Input() showContent!: BuilderEditorProps["showContent"];
  @Input() contentWrapper!: BuilderEditorProps["contentWrapper"];
  @Input() context!: BuilderEditorProps["context"];
  @Input() contentWrapperProps!: BuilderEditorProps["contentWrapperProps"];

  @ViewChild("elementRef") elementRef!: ElementRef;

  @ViewChild("contentwrapperTemplate", { static: true })
  contentwrapperTemplateRef!: TemplateRef<any>;

  myContent?: any[][];

  mergeNewRootState(newData: Dictionary<any>) {
    const combinedState = {
      ...this.builderContextSignal.rootState,
      ...newData,
    };
    if (this.builderContextSignal.rootSetState) {
      this.builderContextSignal.rootSetState?.(combinedState);
    } else {
      this.builderContextSignal.rootState = combinedState;
    }
  }
  mergeNewContent(newContent: BuilderContent) {
    const newContentValue = {
      ...this.builderContextSignal.content,
      ...newContent,
      data: {
        ...this.builderContextSignal.content?.data,
        ...newContent?.data,
      },
      meta: {
        ...this.builderContextSignal.content?.meta,
        ...newContent?.meta,
        breakpoints:
          newContent?.meta?.breakpoints ||
          this.builderContextSignal.content?.meta?.breakpoints,
      },
    };
    this.builderContextSignal.content = newContentValue;
  }
  get showContentProps() {
    return this.showContent
      ? {}
      : {
          hidden: true,
          "aria-hidden": true,
        };
  }
  ContentWrapper = this.contentWrapper || DynamicDiv;
  processMessage(event: MessageEvent) {
    return createEditorListener({
      model: this.model,
      trustedHosts: this.trustedHosts,
      callbacks: {
        configureSdk: (messageContent) => {
          const { breakpoints, contentId } = messageContent;
          if (
            !contentId ||
            contentId !== this.builderContextSignal.content?.id
          ) {
            return;
          }
          if (breakpoints) {
            this.mergeNewContent({
              meta: {
                breakpoints,
              },
            });
          }
        },
        animation: (animation) => {
          triggerAnimation(animation);
        },
        contentUpdate: (newContent) => {
          this.mergeNewContent(newContent);
        },
      },
    })(event);
  }
  evaluateJsCode() {
    // run any dynamic JS code attached to content
    const jsCode = this.builderContextSignal.content?.data?.jsCode;
    if (jsCode) {
      evaluate({
        code: jsCode,
        context: this.context || {},
        localState: undefined,
        rootState: this.builderContextSignal.rootState,
        rootSetState: this.builderContextSignal.rootSetState,
        /**
         * We don't want to cache the result of the JS code, since it's arbitrary side effect code.
         */
        enableCache: false,
      });
    }
  }
  httpReqsData = {};
  httpReqsPending = {};
  clicked = false;
  onClick(event: any) {
    if (this.builderContextSignal.content) {
      const variationId = this.builderContextSignal.content?.testVariationId;
      const contentId = this.builderContextSignal.content?.id;
      _track({
        type: "click",
        canTrack: getDefaultCanTrack(this.canTrack),
        contentId,
        apiKey: this.apiKey,
        variationId: variationId !== contentId ? variationId : undefined,
        ...getInteractionPropertiesForEvent(event),
        unique: !this.clicked,
      });
    }
    if (!this.clicked) {
      this.clicked = true;
    }
  }
  runHttpRequests() {
    const requests: {
      [key: string]: string;
    } = this.builderContextSignal.content?.data?.httpRequests ?? {};
    Object.entries(requests).forEach(([key, url]) => {
      if (!url) return;

      // request already in progress
      if (this.httpReqsPending[key]) return;

      // request already completed, and not in edit mode
      if (this.httpReqsData[key] && !isEditing()) return;
      this.httpReqsPending[key] = true;
      const evaluatedUrl = url.replace(/{{([^}]+)}}/g, (_match, group) =>
        String(
          evaluate({
            code: group,
            context: this.context || {},
            localState: undefined,
            rootState: this.builderContextSignal.rootState,
            rootSetState: this.builderContextSignal.rootSetState,
            enableCache: true,
          })
        )
      );
      fetch(evaluatedUrl)
        .then((response) => response.json())
        .then((json) => {
          this.mergeNewRootState({
            [key]: json,
          });
          this.httpReqsData[key] = true;
        })
        .catch((err) => {
          console.error("error fetching dynamic data", url, err);
        })
        .finally(() => {
          this.httpReqsPending[key] = false;
        });
    });
  }
  emitStateUpdate() {
    if (isEditing()) {
      window.dispatchEvent(
        new CustomEvent<BuilderComponentStateChange>(
          "builder:component:stateChange",
          {
            detail: {
              state: fastClone(this.builderContextSignal.rootState),
              ref: {
                name: this.model,
              },
            },
          }
        )
      );
    }
  }
  node_1_state_ContentWrapper = null;
  mergedInputs_5xe0fc = null;

  constructor(private vcRef: ViewContainerRef) {}

  ngOnInit() {
    this.node_1_state_ContentWrapper = getWrapperClassName(
      this.content?.testVariationId || this.content?.id
    );
    this.mergedInputs_5xe0fc = {
      ref: this.elementRef,
      onClick: this.onClick.bind(this),
      "builder-content-id": this.builderContextSignal.content?.id,
      "builder-model": this.model,
      ...this.showContentProps,
      ...this.contentWrapperProps,
      class: this.node_1_state_ContentWrapper,
    };

    if (typeof window !== "undefined") {
      const onMountHook_0 = () => {
        if (isBrowser()) {
          if (isEditing()) {
            window.addEventListener("message", this.processMessage.bind(this));
            registerInsertMenu();
            setupBrowserForEditing({
              ...(this.locale
                ? {
                    locale: this.locale,
                  }
                : {}),
              ...(this.enrich
                ? {
                    enrich: this.enrich,
                  }
                : {}),
              ...(this.trustedHosts
                ? {
                    trustedHosts: this.trustedHosts,
                  }
                : {}),
            });
            Object.values<ComponentInfo>(
              this.builderContextSignal.componentInfos
            ).forEach((registeredComponent) => {
              const message =
                createRegisterComponentMessage(registeredComponent);
              window.parent?.postMessage(message, "*");
            });
            window.addEventListener(
              "builder:component:stateChangeListenerActivated",
              this.emitStateUpdate
            );
          }
          const shouldTrackImpression =
            this.builderContextSignal.content &&
            getDefaultCanTrack(this.canTrack);
          if (shouldTrackImpression) {
            const variationId =
              this.builderContextSignal.content?.testVariationId;
            const contentId = this.builderContextSignal.content?.id;
            const apiKeyProp = this.apiKey;
            _track({
              type: "impression",
              canTrack: true,
              contentId,
              apiKey: apiKeyProp!,
              variationId: variationId !== contentId ? variationId : undefined,
            });
          }

          /**
           * Override normal content in preview mode.
           * We ignore this when editing, since the edited content is already being sent from the editor via post messages.
           */
          if (isPreviewing() && !isEditing()) {
            const searchParams = new URL(location.href).searchParams;
            const searchParamPreviewModel = searchParams.get("builder.preview");
            const searchParamPreviewId = searchParams.get(
              `builder.overrides.${searchParamPreviewModel}`
            );
            const previewApiKey =
              searchParams.get("apiKey") || searchParams.get("builder.space");

            /**
             * Make sure that:
             * - the preview model name is the same as the one we're rendering, since there can be multiple models rendered
             *  at the same time, e.g. header/page/footer.
             * - the API key is the same, since we don't want to preview content from other organizations.
             * - if there is content, that the preview ID is the same as that of the one we receive.
             *
             * TO-DO: should we only update the state when there is a change?
             **/
            if (
              searchParamPreviewModel === this.model &&
              previewApiKey === this.apiKey &&
              (!this.content || searchParamPreviewId === this.content.id)
            ) {
              fetchOneEntry({
                model: this.model,
                apiKey: this.apiKey,
                apiVersion: this.builderContextSignal.apiVersion,
              }).then((content) => {
                if (content) {
                  this.mergeNewContent(content);
                }
              });
            }
          }
        }
      };
      onMountHook_0();
      const onMountHook_1 = () => {
        if (!this.apiKey) {
          logger.error(
            "No API key provided to `Content` component. This can cause issues. Please provide an API key using the `apiKey` prop."
          );
        }
        this.evaluateJsCode();
        this.runHttpRequests();
        this.emitStateUpdate();
      };
      onMountHook_1();
    }

    this.myContent = [
      this.vcRef.createEmbeddedView(this.contentwrapperTemplateRef).rootNodes,
    ];
  }

  ngOnChanges() {
    if (typeof window !== "undefined") {
      if (this.content) {
        this.mergeNewContent(this.content);
      }
      this.evaluateJsCode();
      this.runHttpRequests();
      this.emitStateUpdate();
      if (this.data) {
        this.mergeNewRootState(this.data);
      }
      if (this.locale) {
        this.mergeNewRootState({
          locale: this.locale,
        });
      }
      this.node_1_state_ContentWrapper = getWrapperClassName(
        this.content?.testVariationId || this.content?.id
      );
      this.mergedInputs_5xe0fc = {
        ref: this.elementRef,
        onClick: this.onClick.bind(this),
        "builder-content-id": this.builderContextSignal.content?.id,
        "builder-model": this.model,
        ...this.showContentProps,
        ...this.contentWrapperProps,
        class: this.node_1_state_ContentWrapper,
      };
    }
  }

  ngOnDestroy() {
    if (isBrowser()) {
      window.removeEventListener("message", this.processMessage);
      window.removeEventListener(
        "builder:component:stateChangeListenerActivated",
        this.emitStateUpdate
      );
    }
  }
}

// examples/react-native/src/sdk-broken/src/components/content/components/enable-editor.jsx
"use client";
import * as React from "react";
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
} from "react-native";
import { useState, useContext, useRef, useEffect } from "react";
import { evaluate } from "../../../functions/evaluate";
import { fetch } from "../../../functions/get-fetch.js";
import { isBrowser } from "../../../functions/is-browser.js";
import { isEditing } from "../../../functions/is-editing.js";
import { createRegisterComponentMessage } from "../../../functions/register-component.js";
import { _track } from "../../../functions/track/index.js";
import builderContext from "../../../context/builder.context";
import {
  registerInsertMenu,
  setupBrowserForEditing,
} from "../../../scripts/init-editing.js";
import { checkIsDefined } from "../../../helpers/nullable.js";
import { getInteractionPropertiesForEvent } from "../../../functions/track/interaction.js";
import { logger } from "../../../helpers/logger.js";
import { getContent } from "../../../functions/get-content/index.js";
import { isPreviewing } from "../../../functions/is-previewing.js";
import { postPreviewContent } from "../../../helpers/preview-lru-cache/set.js";

function EnableEditor(props) {
  const elementRef = useRef(null);
  const [canTrackToUse, setCanTrackToUse] = useState(() =>
    checkIsDefined(props.canTrack) ? props.canTrack : true
  );

  const [forceReRenderCount, setForceReRenderCount] = useState(() => 0);

  function mergeNewContent(newContent) {
    const newContentValue = {
      ...props.builderContextSignal.content,
      ...newContent,
      data: {
        ...props.builderContextSignal.content?.data,
        ...newContent?.data,
      },
      meta: {
        ...props.builderContextSignal.content?.meta,
        ...newContent?.meta,
        breakpoints:
          newContent?.meta?.breakpoints ||
          props.builderContextSignal.content?.meta?.breakpoints,
      },
    };
    props.builderContextSignal.content = newContentValue;
  }

  const [lastUpdated, setLastUpdated] = useState(() => 0);

  const [shouldSendResetCookie, setShouldSendResetCookie] = useState(
    () => false
  );

  function processMessage(event) {
    const { data } = event;
    if (data) {
      switch (data.type) {
        case "builder.configureSdk": {
          const messageContent = data.data;
          const { breakpoints, contentId } = messageContent;
          if (
            !contentId ||
            contentId !== props.builderContextSignal.content?.id
          ) {
            return;
          }
          if (breakpoints) {
            mergeNewContent({
              meta: {
                breakpoints,
              },
            });
          }
          setForceReRenderCount(forceReRenderCount + 1); // This is a hack to force Qwik to re-render.
          break;
        }
        case "builder.contentUpdate": {
          const messageContent = data.data;
          const key =
            messageContent.key ||
            messageContent.alias ||
            messageContent.entry ||
            messageContent.modelName;
          const contentData = messageContent.data;
          if (key === props.model) {
            mergeNewContent(contentData);
            setForceReRenderCount(forceReRenderCount + 1); // This is a hack to force Qwik to re-render.
          }

          break;
        }
      }
    }
  }

  function evaluateJsCode() {
    // run any dynamic JS code attached to content
    const jsCode = props.builderContextSignal.content?.data?.jsCode;
    if (jsCode) {
      evaluate({
        code: jsCode,
        context: props.context || {},
        localState: undefined,
        rootState: props.builderContextSignal.rootState,
        rootSetState: props.builderContextSignal.rootSetState,
      });
    }
  }

  const [httpReqsData, setHttpReqsData] = useState(() => ({}));

  const [clicked, setClicked] = useState(() => false);

  function onClick(event) {
    if (props.builderContextSignal.content) {
      const variationId = props.builderContextSignal.content?.testVariationId;
      const contentId = props.builderContextSignal.content?.id;
      _track({
        type: "click",
        canTrack: canTrackToUse,
        contentId,
        apiKey: props.apiKey,
        variationId: variationId !== contentId ? variationId : undefined,
        ...getInteractionPropertiesForEvent(event),
        unique: !clicked,
      });
    }
    if (!clicked) {
      setClicked(true);
    }
  }

  function evalExpression(expression) {
    return expression.replace(/{{([^}]+)}}/g, (_match, group) =>
      evaluate({
        code: group,
        context: props.context || {},
        localState: undefined,
        rootState: props.builderContextSignal.rootState,
        rootSetState: props.builderContextSignal.rootSetState,
      })
    );
  }

  function handleRequest({ url, key }) {
    fetch(url)
      .then((response) => response.json())
      .then((json) => {
        const newState = {
          ...props.builderContextSignal.rootState,
          [key]: json,
        };
        props.builderContextSignal.rootSetState?.(newState);
        httpReqsData[key] = true;
      })
      .catch((err) => {
        console.error("error fetching dynamic data", url, err);
      });
  }

  function runHttpRequests() {
    const requests =
      props.builderContextSignal.content?.data?.httpRequests ?? {};
    Object.entries(requests).forEach(([key, url]) => {
      if (url && (!httpReqsData[key] || isEditing())) {
        const evaluatedUrl = evalExpression(url);
        handleRequest({
          url: evaluatedUrl,
          key,
        });
      }
    });
  }

  function emitStateUpdate() {
    if (isEditing()) {
      window.dispatchEvent(
        new CustomEvent("builder:component:stateChange", {
          detail: {
            state: props.builderContextSignal.rootState,
            ref: {
              name: props.model,
            },
          },
        })
      );
    }
  }

  useEffect(() => {
    if (!props.apiKey) {
      logger.error(
        "No API key provided to `RenderContent` component. This can cause issues. Please provide an API key using the `apiKey` prop."
      );
    }
    if (isBrowser()) {
      if (isEditing()) {
        setForceReRenderCount(forceReRenderCount + 1);
        window.addEventListener("message", processMessage);
        registerInsertMenu();
        setupBrowserForEditing({
          ...(props.locale
            ? {
                locale: props.locale,
              }
            : {}),
          ...(props.includeRefs
            ? {
                includeRefs: props.includeRefs,
              }
            : {}),
          ...(props.enrich
            ? {
                enrich: props.enrich,
              }
            : {}),
        });
        Object.values(props.builderContextSignal.componentInfos).forEach(
          (registeredComponent) => {
            const message = createRegisterComponentMessage(registeredComponent);
            window.parent?.postMessage(message, "*");
          }
        );
        window.addEventListener(
          "builder:component:stateChangeListenerActivated",
          emitStateUpdate
        );
      }
      if (props.builderContextSignal.content) {
        const variationId = props.builderContextSignal.content?.testVariationId;
        const contentId = props.builderContextSignal.content?.id;
        _track({
          type: "impression",
          canTrack: canTrackToUse,
          contentId,
          apiKey: props.apiKey,
          variationId: variationId !== contentId ? variationId : undefined,
        });
      }
      // override normal content in preview mode
      if (isPreviewing()) {
        const searchParams = new URL(location.href).searchParams;
        const searchParamPreviewModel = searchParams.get("builder.preview");
        const searchParamPreviewId = searchParams.get(
          `builder.preview.${searchParamPreviewModel}`
        );
        const previewApiKey =
          searchParams.get("apiKey") || searchParams.get("builder.space");

        /**
         * Make sure that:
         * - the preview model name is the same as the one we're rendering, since there can be multiple models rendered  *  at the same time, e.g. header/page/footer.  * - the API key is the same, since we don't want to preview content from other organizations.
         * - if there is content, that the preview ID is the same as that of the one we receive.
         *
         * TO-DO: should we only update the state when there is a change?
         **/
        if (
          searchParamPreviewModel === props.model &&
          previewApiKey === props.apiKey &&
          (!props.content || searchParamPreviewId === props.content.id)
        ) {
          getContent({
            model: props.model,
            apiKey: props.apiKey,
            apiVersion: props.builderContextSignal.apiVersion,
          }).then((content) => {
            if (content) {
              mergeNewContent(content);
            }
          });
        }
      }
      evaluateJsCode();
      runHttpRequests();
      emitStateUpdate();
    }
  }, []);

  useEffect(() => {
    if (props.content) {
      mergeNewContent(props.content);
    }
  }, [props.content]);
  useEffect(() => {}, [shouldSendResetCookie]);
  useEffect(() => {
    evaluateJsCode();
  }, [
    props.builderContextSignal.content?.data?.jsCode,
    props.builderContextSignal.rootState,
  ]);
  useEffect(() => {
    runHttpRequests();
  }, [props.builderContextSignal.content?.data?.httpRequests]);
  useEffect(() => {
    emitStateUpdate();
  }, [props.builderContextSignal.rootState]);

  useEffect(() => {
    return () => {
      if (isBrowser()) {
        window.removeEventListener("message", processMessage);
        window.removeEventListener(
          "builder:component:stateChangeListenerActivated",
          emitStateUpdate
        );
      }
    };
  }, []);

  return (
    <builderContext.Provider value={props.builderContextSignal}>
      {props.builderContextSignal.content ? (
        <>
          <View
            key={forceReRenderCount}
            ref={elementRef}
            onClick={(event) => onClick(event)}
            builder-content-id={props.builderContextSignal.content?.id}
            builder-model={props.model}
            {...{
              // currently, we can't set the actual ID here. // we don't need it right now, we just need to identify content divs for testing.
              dataSet: {
                "builder-content-id": "",
              },
            }}
            {...(props.showContent
              ? {}
              : {
                  hidden: true,
                  "aria-hidden": true,
                })}
          >
            {props.children}
          </View>
        </>
      ) : null}
    </builderContext.Provider>
  );
}

export default EnableEditor;
