// packages/sdks/output/svelte/src/blocks/img.svelte
<script>
    
    
    
    
  import  {  isEditing  }  from '../functions/is-editing';

  


    
    export let backgroundSize;
export let backgroundPosition;
export let attributes;
export let imgSrc;
export let altText;

    
    

    

    

    

    
  </script>

  <img {...attributes} style={{
objectFit: backgroundSize || 'cover',
objectPosition: backgroundPosition || 'center'
}}  key={isEditing() && imgSrc || 'default-key'}  alt={altText}  src={imgSrc}  />

// packages/sdks/output/solid/src/blocks/img/img.jsx
import { isEditing } from "../../functions/is-editing";

function ImgComponent(props) {
  return <img {...props.attributes} style={{
    "object-fit": props.backgroundSize || "cover",
    "object-position": props.backgroundPosition || "center"
  }} key={isEditing() && props.imgSrc || "default-key"} alt={props.altText} src={props.imgSrc} />;
}

export default ImgComponent;
