// packages/sdks/snippets/react/src/routes/blueprints/homepage.tsx
import {
  BuilderContent,
  Content,
  fetchOneEntry,
  isPreviewing,
} from '@builder.io/sdk-react';
import { useEffect, useState } from 'react';

export default function Homepage() {
  const [content, setContent] = useState<BuilderContent | null>(null);

  useEffect(() => {
    fetchOneEntry({
      model: 'homepage',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    }).then((content) => setContent(content));
  }, []);

  if (!content && !isPreviewing()) {
    return <div>404</div>;
  }

  return (
    <Content
      apiKey="ee9f13b4981e489a9a1209887695ef2b"
      model="homepage"
      content={content}
    />
  );
}

// packages/sdks/snippets/angular-17-ssr/src/app/home/homepage.component.ts
import { Component } from '@angular/core';
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type BuilderContent,
} from '@builder.io/sdk-angular';

@Component({
  selector: 'app-homepage',
  standalone: true,
  imports: [Content],
  template: `
    @if (content || isPreviewing()) {
      <builder-content
        [model]="model"
        [content]="content"
        [apiKey]="apiKey"
      ></builder-content>
    } @else {
      <div>404</div>
    }
  `,
})
export class HomepageComponent {
  content: BuilderContent | null = null;

  model = 'homepage';
  apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  isPreviewing = isPreviewing;

  async ngOnInit() {
    this.content = await fetchOneEntry({
      model: this.model,
      apiKey: this.apiKey,
    });
  }
}
