// packages/sdks/snippets/angular-17/src/app/product-details/product-details.component.ts
import { Component } from '@angular/core';
import { fetchOneEntry, type BuilderContent } from '@builder.io/sdk-angular';

@Component({
  selector: 'app-product-details',
  standalone: true,
  imports: [],
  template: `
    @if (productDetails) {
      <div>
        <h1>{{ productDetails.data?.['name'] }}</h1>
        <img
          [src]="productDetails.data?.['image']"
          [alt]="productDetails.data?.['name']"
        />
        <p>{{ productDetails.data?.['collection'].value.data.copy }}</p>
        <p>
          Price:
          {{ productDetails.data?.['collection'].value.data.price }}
        </p>
      </div>
    } @else {
      <div>
        <p>Loading product details...</p>
      </div>
    }
  `,
})
export class ProductDetailsComponent {
  productDetails: BuilderContent | null = null;
  apiKey: string = 'ee9f13b4981e489a9a1209887695ef2b';

  async ngOnInit() {
    this.productDetails = await fetchOneEntry({
      model: 'product-details',
      apiKey: this.apiKey,
      query: {
        'data.handle': 'jacket',
      },
    });
  }
}

// packages/sdks/snippets/vue/src/views/blueprints/ProductDetails.vue
<template>
    <div v-if="!productDetails">
      <p>Loading product details...</p>
    </div>
    <div class="product-details-page" v-else>
      <h1>{{ productDetails.data?.['name'] }}</h1>
      <img
        :src="productDetails.data?.['image']"
        :alt="productDetails.data?.['name']"
      />
      <p>{{ productDetails.data?.['collection'].value.data.copy }}</p>
      <p>Price: {{ productDetails.data?.['collection'].value.data.price }}</p>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, onMounted } from 'vue'
  import { fetchOneEntry, BuilderContent } from '@builder.io/sdk-vue'
  
  const productDetails = ref<BuilderContent | null>(null);
  
  onMounted( () => {
    fetchOneEntry({
        model: 'product-details',
        apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
        query: { 'data.handle': 'jacket' },
      }).then((data) => {
        productDetails.value = data
      })
  })
  </script>
