// packages/sdks/output/angular/src/components/content-variants/content-variants.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

type VariantsProviderProps = ContentVariantsPrps & {
  /**
   * For internal use only. Do not provide this prop.
   */
  isNestedRender?: boolean;
};

import { TARGET } from "../../constants/target";
import { handleABTestingSync } from "../../helpers/ab-tests";
import { getDefaultCanTrack } from "../../helpers/canTrack";
import ContentComponent from "../content/content";
import InlinedScript from "../inlined-script";
import InlinedStyles from "../inlined-styles";
import type { ContentVariantsPrps } from "./content-variants.types";
import {
  checkShouldRenderVariants,
  getInitVariantsFnsScriptString,
  getUpdateCookieAndStylesScript,
  getVariants,
} from "./helpers";

@Component({
  selector: "content-variants, ContentVariants",
  template: `
    <ng-container>
      <ng-container *ngIf="!isNestedRender && TARGET !== 'reactNative'">
        <InlinedScript
          id="builderio-init-variants-fns"
          [scriptStr]="node_0_InlinedScript"
          [nonce]="nonce || ''"
        ></InlinedScript>
      </ng-container>
      <ng-container *ngIf="shouldRenderVariants">
        <InlinedStyles
          id="builderio-variants"
          [styles]="hideVariantsStyleString"
          [nonce]="nonce || ''"
        ></InlinedStyles>
        <InlinedScript
          id="builderio-variants-visibility"
          [scriptStr]="updateCookieAndStylesScriptStr"
          [nonce]="nonce || ''"
        ></InlinedScript>
        <ng-container
          *ngFor="let variant of getVariants(content); trackBy: trackByVariant0"
        >
          <ContentComponent
            [isNestedRender]="isNestedRender"
            [nonce]="nonce"
            [content]="variant"
            [showContent]="false"
            [model]="model"
            [data]="data"
            [context]="context"
            [apiKey]="apiKey"
            [apiVersion]="apiVersion"
            [customComponents]="customComponents"
            [linkComponent]="linkComponent"
            [canTrack]="canTrack"
            [locale]="locale"
            [enrich]="enrich"
            [isSsrAbTest]="shouldRenderVariants"
            [blocksWrapper]="blocksWrapper"
            [blocksWrapperProps]="blocksWrapperProps"
            [contentWrapper]="contentWrapper"
            [contentWrapperProps]="contentWrapperProps"
            [trustedHosts]="trustedHosts"
          ></ContentComponent>
        </ng-container>
      </ng-container>
      <ContentComponent
        [nonce]="nonce"
        [isNestedRender]="isNestedRender"
        [content]="defaultContent"
        [showContent]="true"
        [model]="model"
        [data]="data"
        [context]="context"
        [apiKey]="apiKey"
        [apiVersion]="apiVersion"
        [customComponents]="customComponents"
        [linkComponent]="linkComponent"
        [canTrack]="canTrack"
        [locale]="locale"
        [enrich]="enrich"
        [isSsrAbTest]="shouldRenderVariants"
        [blocksWrapper]="blocksWrapper"
        [blocksWrapperProps]="blocksWrapperProps"
        [contentWrapper]="contentWrapper"
        [contentWrapperProps]="contentWrapperProps"
        [trustedHosts]="trustedHosts"
      ></ContentComponent>
    </ng-container>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, InlinedScript, InlinedStyles, ContentComponent],
})
export default class ContentVariants {
  TARGET = TARGET;
  getVariants = getVariants;

  @Input() canTrack!: VariantsProviderProps["canTrack"];
  @Input() content!: VariantsProviderProps["content"];
  @Input() isNestedRender!: VariantsProviderProps["isNestedRender"];
  @Input() nonce!: VariantsProviderProps["nonce"];
  @Input() model!: VariantsProviderProps["model"];
  @Input() data!: VariantsProviderProps["data"];
  @Input() context!: VariantsProviderProps["context"];
  @Input() apiKey!: VariantsProviderProps["apiKey"];
  @Input() apiVersion!: VariantsProviderProps["apiVersion"];
  @Input() customComponents!: VariantsProviderProps["customComponents"];
  @Input() linkComponent!: VariantsProviderProps["linkComponent"];
  @Input() locale!: VariantsProviderProps["locale"];
  @Input() enrich!: VariantsProviderProps["enrich"];
  @Input() blocksWrapper!: VariantsProviderProps["blocksWrapper"];
  @Input() blocksWrapperProps!: VariantsProviderProps["blocksWrapperProps"];
  @Input() contentWrapper!: VariantsProviderProps["contentWrapper"];
  @Input() contentWrapperProps!: VariantsProviderProps["contentWrapperProps"];
  @Input() trustedHosts!: VariantsProviderProps["trustedHosts"];

  shouldRenderVariants = checkShouldRenderVariants({
    canTrack: getDefaultCanTrack(this.canTrack),
    content: this.content,
  });
  get updateCookieAndStylesScriptStr() {
    return getUpdateCookieAndStylesScript(
      getVariants(this.content).map((value) => ({
        id: value.testVariationId!,
        testRatio: value.testRatio,
      })),
      this.content?.id || ""
    );
  }
  get hideVariantsStyleString() {
    return getVariants(this.content)
      .map((value) => `.variant-${value.testVariationId} { display: none; } `)
      .join("");
  }
  get defaultContent() {
    return this.shouldRenderVariants
      ? {
          ...this.content,
          testVariationId: this.content?.id,
        }
      : handleABTestingSync({
          item: this.content,
          canTrack: getDefaultCanTrack(this.canTrack),
        });
  }
  node_0_InlinedScript = null;
  trackByVariant0(_, variant) {
    return variant.testVariationId;
  }

  ngOnInit() {
    this.shouldRenderVariants = checkShouldRenderVariants({
      canTrack: getDefaultCanTrack(this.canTrack),
      content: this.content,
    });
    this.node_0_InlinedScript = getInitVariantsFnsScriptString();

    if (typeof window !== "undefined") {
      /**
       * For Solid/Svelte: we unmount the non-winning variants post-hydration.
       */
    }
  }

  ngOnChanges() {
    if (typeof window !== "undefined") {
      this.node_0_InlinedScript = getInitVariantsFnsScriptString();
    }
  }
}

// examples/react-native/src/sdk-broken/src/components/content-variants/content-variants.jsx
"use client";
import * as React from "react";
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
} from "react-native";
import { useState, useEffect } from "react";
import {
  checkShouldRunVariants,
  getScriptString,
  getVariants,
  getVariantsScriptString,
} from "./helpers.js";
import ContentComponent from "../content/content";
import { getDefaultCanTrack } from "../../helpers/canTrack.js";
import InlinedStyles from "../inlined-styles";
import { handleABTestingSync } from "../../helpers/ab-tests.js";
import InlinedScript from "../inlined-script";
import { TARGET } from "../../constants/target.js";

function ContentVariants(props) {
  const [shouldRenderVariants, setShouldRenderVariants] = useState(() =>
    checkShouldRunVariants({
      canTrack: getDefaultCanTrack(props.canTrack),
      content: props.content,
    })
  );

  function variantScriptStr() {
    return getVariantsScriptString(
      getVariants(props.content).map((value) => ({
        id: value.testVariationId,
        testRatio: value.testRatio,
      })),
      props.content?.id || ""
    );
  }

  function hideVariantsStyleString() {
    return getVariants(props.content)
      .map((value) => `.variant-${value.testVariationId} { display: none; } `)
      .join("");
  }

  function defaultContent() {
    return shouldRenderVariants
      ? {
          ...props.content,
          testVariationId: props.content?.id,
        }
      : handleABTestingSync({
          item: props.content,
          canTrack: getDefaultCanTrack(props.canTrack),
        });
  }

  useEffect(() => {
    /**
     * We unmount the non-winning variants post-hydration in Vue.
     */
  }, []);

  return (
    <>
      {!props.__isNestedRender && TARGET !== "reactNative" ? (
        <>
          <InlinedScript scriptStr={getScriptString()} />
        </>
      ) : null}

      {shouldRenderVariants ? (
        <>
          <InlinedStyles
            id={`variants-styles-${props.content?.id}`}
            styles={hideVariantsStyleString()}
          />
          <InlinedScript scriptStr={variantScriptStr()} />
          {getVariants(props.content)?.map((variant) => (
            <ContentComponent
              key={variant.testVariationId}
              content={variant}
              showContent={false}
              classNameProp={undefined}
              model={props.model}
              data={props.data}
              context={props.context}
              apiKey={props.apiKey}
              apiVersion={props.apiVersion}
              customComponents={props.customComponents}
              canTrack={props.canTrack}
              locale={props.locale}
              includeRefs={props.includeRefs}
              enrich={props.enrich}
              isSsrAbTest={shouldRenderVariants}
            />
          ))}
        </>
      ) : null}

      <ContentComponent
        {...{}}
        content={defaultContent()}
        classNameProp={`variant-${props.content?.id}`}
        showContent={true}
        model={props.model}
        data={props.data}
        context={props.context}
        apiKey={props.apiKey}
        apiVersion={props.apiVersion}
        customComponents={props.customComponents}
        canTrack={props.canTrack}
        locale={props.locale}
        includeRefs={props.includeRefs}
        enrich={props.enrich}
        isSsrAbTest={shouldRenderVariants}
      />
    </>
  );
}

export default ContentVariants;
