// packages/sdks/output/solid/src/blocks/button.lite.tsx
import { Show } from "solid-js";

export default function Button(props) {
  return (
    <>
      <Show when={props.link}>
        <a
          {...props.attributes}
          role="button"
          href={props.link}
          target={props.openLinkInNewTab ? "_blank" : undefined}
        >
          {props.text}
        </a>
      </Show>
    </>
  );
}

// packages/sdks/output/react-native/src/blocks/button.lite.tsx
import * as React from "react";
import { View, StyleSheet, Image, Text } from "react-native";

export default function Button(props) {
  return (
    <View
      {...props.attributes}
      role="button"
      href={props.link}
      target={props.openLinkInNewTab ? "_blank" : undefined}
    >
      <Text>{props.text}</Text>
    </View>
  );
}
