// packages/sdks/output/vue/nuxt2/src/components/render-block/block-styles.vue
<template>
  <render-inlined-styles :styles="css"></render-inlined-styles>
</template>
<script>
import RenderInlinedStyles from "../render-inlined-styles";

export default {
  name: "block-styles",
  components: { "render-inlined-styles": async () => RenderInlinedStyles },
  props: ["block"],

  computed: {
    css() {
      // TODO: media queries
      const styleObject = this.block.responsiveStyles?.large;

      if (!styleObject) {
        return "";
      }

      let str = `.${this.block.id} {`;

      for (const key in styleObject) {
        const value = styleObject[key];

        if (typeof value === "string") {
          str += `${this.camelToKebabCase(key)}: ${value};`;
        }
      }

      str += "}";
      return str;
    },
  },

  methods: {
    camelToKebabCase(string) {
      return string
        .replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, "$1-$2")
        .toLowerCase();
    },
  },
};
</script>

// packages/sdks/output/svelte/src/components/render-block/block-styles.svelte
<script>
    
    
    
    
  import  RenderInlinedStyles,  {  }  from '../render-inlined-styles.svelte';

  

    

    
    export let block;
    
    function camelToKebabCase(string) {
return string.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, '$1-$2').toLowerCase();
}
    $: css = () => {
// TODO: media queries
const styleObject = block.responsiveStyles?.large;

if (!styleObject) {
  return '';
}

let str = `.${block.id} {`;

for (const key in styleObject) {
  const value = styleObject[key];

  if (typeof value === 'string') {
    str += `${camelToKebabCase(key)}: ${value};`;
  }
}

str += '}';
return str;
};

    
    
    

    

    

    
  </script>

  <RenderInlinedStyles  styles={css()} ></RenderInlinedStyles>
