// packages/sdks/output/solid/src/components/render-block/render-component-and-styles.jsx
import { Show, For } from "solid-js";
import { Dynamic } from "solid-js/web";
import { TARGET } from "../../constants/target.js";
import BlockStyles from "./block-styles";
import RenderBlock from "./render-block";

function RenderComponentAndStyles(props) {
  return <>
      <Show when={TARGET === "vue" || TARGET === "svelte"}>
        <BlockStyles block={props.block}></BlockStyles>
      </Show>
      <Show when={props.componentRef}>
        <Dynamic {...props.componentOptions} component={props.componentRef}>
          <For each={props.blockChildren}>
            {(child, _index) => {
            const index = _index();

            return <RenderBlock key={child.id} block={child}></RenderBlock>;
          }}
          </For>
        </Dynamic>
      </Show>
    </>;
}

export default RenderComponentAndStyles;

// packages/sdks/output/svelte/src/components/render-block/render-component-and-styles.svelte
<script>
  
  
  
  
import  {  TARGET  }  from '../../constants/target.js';
import  BlockStyles,  {  }  from './block-styles.svelte';
import  RenderBlock,  {  }  from './render-block.svelte';



  

  
  export let block;
export let componentRef;
export let componentOptions;
export let blockChildren;
  
  
  

  
  
  

  

  

  
</script>


  

{#if TARGET === 'vue' || TARGET === 'svelte' }

    
<BlockStyles  block={block} ></BlockStyles>

  


{/if}

  

{#if componentRef }
<svelte:component {...componentOptions} this={componentRef} >
      

{#each blockChildren as child, index }
<RenderBlock  key={child.id}  block={child} ></RenderBlock>
{/each}


    </svelte:component>


{/if}
