// packages/sdks/output/vue/nuxt2/src/components/render-block/render-component.vue
<template>
  <component v-bind="componentOptions" v-if="componentRef" :is="componentRef">
    <render-block
      v-for="(child, index) in blockChildren"
      :block="child"
      :key="'render-block-' + child.id"
    ></render-block>
    <block-styles
      v-for="(child, index) in blockChildren"
      :block="child"
      :key="'block-style-' + child.id"
    ></block-styles>
  </component>
</template>
<script>
import BlockStyles from "./block-styles";
import RenderBlock from "./render-block";

export default {
  name: "render-component",
  components: {
    "render-block": async () => RenderBlock,
    "block-styles": async () => BlockStyles,
  },
  props: ["componentRef", "componentOptions", "blockChildren"],
};
</script>

// packages/sdks/output/svelte/src/components/render-block/render-component.svelte
<script>
  
  
  
  
import  BlockStyles,  {  }  from './block-styles.svelte';
import  RenderBlock,  {  }  from './render-block.svelte';



  

  
  export let componentRef;
export let componentOptions;
export let blockChildren;
  
  
  

  
  
  

  

  

  
</script>


{#if componentRef }

  
<svelte:component {...componentOptions} this={componentRef} >
    

    

{#each blockChildren as child, index }
<RenderBlock  key={'render-block-' + child.id}  block={child} ></RenderBlock>
{/each}


    

{#each blockChildren as child, index }
<BlockStyles  key={'block-style-' + child.id}  block={child} ></BlockStyles>
{/each}


  </svelte:component>




{/if}
