// packages/sdks/output/svelte/src/blocks/section.svelte
<script>
    
    
    
    
  
  


    
    export let attributes;
export let maxWidth;
export let children;

    
    

    

    

    

    
  </script>

  <section {...attributes} style={maxWidth && typeof maxWidth === 'number' ? {
maxWidth: maxWidth
} : undefined} >
    
<slot></slot>

  </section>

// packages/sdks/output/vue/nuxt2/src/blocks/section/section.vue
<template>
  <section
    v-bind="attributes"
    :style="
      maxWidth && typeof maxWidth === 'number'
        ? {
            maxWidth: maxWidth,
          }
        : undefined
    "
  >
    <slot></slot>
  </section>
</template>
<script>
export default {
  name: "builder-section-component",

  props: ["attributes", "maxWidth"],
};
</script>
