// examples/react-v2/src/sdk-src/components/content/components/styles.tsx
"use client";
import * as React from "react";
import { useState } from "react";

interface Props {
  cssCode?: string;
  customFonts?: CustomFont[];
  contentId?: string;
  isNestedRender?: boolean;
}

import InlinedStyles from "../../inlined-styles";
import type { CustomFont } from "./styles.helpers.js";
import { getCss, getDefaultStyles, getFontCss } from "./styles.helpers.js";

function ContentStyles(props: Props) {
  const [injectedStyles, setInjectedStyles] = useState(() =>
    `
${getCss({
  cssCode: props.cssCode,
  contentId: props.contentId,
})}
${getFontCss({
  customFonts: props.customFonts,
})}
${getDefaultStyles(props.isNestedRender)}
`.trim()
  );

  return <InlinedStyles id="builderio-content" styles={injectedStyles} />;
}

export default ContentStyles;

// packages/sdks/output/angular/src/components/content/components/styles.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

interface Props extends BuilderNonceProp {
  cssCode?: string;
  customFonts?: CustomFont[];
  contentId?: string;
  isNestedRender?: boolean;
}

import type { BuilderNonceProp } from "../../../types/builder-props";
import InlinedStyles from "../../inlined-styles";
import type { CustomFont } from "./styles.helpers";
import { getCss, getDefaultStyles, getFontCss } from "./styles.helpers";

@Component({
  selector: "content-styles, ContentStyles",
  template: `
    <inlined-styles
      id="builderio-content"
      [styles]="injectedStyles"
      [nonce]="nonce"
    ></inlined-styles>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, InlinedStyles],
})
export default class ContentStyles {
  @Input() cssCode!: Props["cssCode"];
  @Input() contentId!: Props["contentId"];
  @Input() customFonts!: Props["customFonts"];
  @Input() isNestedRender!: Props["isNestedRender"];
  @Input() nonce!: Props["nonce"];

  injectedStyles = `
${getCss({
  cssCode: this.cssCode,
  contentId: this.contentId,
})}
${getFontCss({
  customFonts: this.customFonts,
})}
${getDefaultStyles(this.isNestedRender)}
`.trim();

            ngOnInit() {
              this.injectedStyles = `
${getCss({
  cssCode: this.cssCode,
  contentId: this.contentId,
})}
${getFontCss({
  customFonts: this.customFonts,
})}
${getDefaultStyles(this.isNestedRender)}
`.trim();
            }
          }
