// packages/sdks/snippets/react-sdk-next-14-app/app/components/CustomColumns.tsx
'use client';

import {
  Blocks,
  type BuilderBlock,
  type RegisteredComponent,
  type RegisteredComponents,
} from '@builder.io/sdk-react';
import React from 'react';

type CustomColumnsProps = {
  column1: BuilderBlock[];
  column2: BuilderBlock[];
  builderBlock: BuilderBlock;
  builderComponents: RegisteredComponents;
};

export function CustomColumns({
  column1,
  column2,
  builderBlock,
  builderComponents,
}: CustomColumnsProps) {
  return (
    <>
      <Blocks
        blocks={column1}
        path="column1"
        parent={builderBlock.id}
        registeredComponents={builderComponents}
      />
      <Blocks
        blocks={column2}
        path="column2"
        parent={builderBlock.id}
        registeredComponents={builderComponents}
      />
    </>
  );
}

export const customColumnsInfo: RegisteredComponent = {
  name: 'MyColumns',
  component: CustomColumns,
  shouldReceiveBuilderProps: { builderBlock: true, builderComponents: true },
  inputs: [
    { name: 'column1', type: 'uiBlocks', defaultValue: [] },
    { name: 'column2', type: 'uiBlocks', defaultValue: [] },
  ],
};

// packages/sdks/snippets/angular-17-ssr/src/app/editable-regions/custom-columns/custom-columns.component.ts
import { Component, Input } from '@angular/core';
import type {
  BuilderBlock,
  BuilderContextInterface,
  RegisteredComponent,
  RegisteredComponents,
} from '@builder.io/sdk-angular';
import { Blocks } from '@builder.io/sdk-angular';

@Component({
  selector: 'app-custom-columns',
  standalone: true,
  imports: [Blocks],
  template: `
    <blocks
      [blocks]="column1"
      [path]="'column1'"
      [parent]="builderBlock.id"
      [context]="builderContext"
      [registeredComponents]="builderComponents"
    />
    <blocks
      [blocks]="column2"
      [path]="'column2'"
      [parent]="builderBlock.id"
      [context]="builderContext"
      [registeredComponents]="builderComponents"
    />
  `,
})
export class CustomColumnsComponent {
  @Input() builderBlock!: BuilderBlock;
  @Input() column1!: BuilderBlock[];
  @Input() column2!: BuilderBlock[];
  @Input() builderComponents!: RegisteredComponents;
  @Input() builderContext!: BuilderContextInterface;
}

export const customColumnsInfo: RegisteredComponent = {
  name: 'MyColumns',
  component: CustomColumnsComponent,
  inputs: [
    {
      name: 'column1',
      type: 'uiBlocks',
      defaultValue: [],
    },
    {
      name: 'column2',
      type: 'uiBlocks',
      defaultValue: [],
    },
  ],

  shouldReceiveBuilderProps: {
    builderBlock: true,
    builderComponents: true,
    builderContext: true,
  },
};
