// packages/sdks/output/solid/src/blocks/columns/columns.lite.tsx
import { For } from "solid-js";

import { createMutable } from "solid-js/store";
import { css } from "solid-styled-components";

import RenderBlocks from "../../components/render-blocks.lite";

function Columns(props) {
  const state = createMutable({
    getGutterSize() {
      return typeof props.space === "number" ? props.space || 0 : 20;
    },
    getColumns() {
      return props.columns || [];
    },
    getWidth(index: number) {
      const columns = this.getColumns();
      return columns[index]?.width || 100 / columns.length;
    },
    getColumnCssWidth(index: number) {
      const columns = this.getColumns();
      const gutterSize = this.getGutterSize();
      const subtractWidth =
        (gutterSize * (columns.length - 1)) / columns.length;
      return `calc(${this.getWidth(index)}% - ${subtractWidth}px)`;
    },
    maybeApplyForTablet(prop: string) {
      const _stackColumnsAt = props.stackColumnsAt || "tablet";

      return _stackColumnsAt === "tablet" ? prop : "inherit";
    },
    get columnsCssVars() {
      const flexDir =
        props.stackColumnsAt === "never"
          ? "inherit"
          : props.reverseColumnsWhenStacked
          ? "column-reverse"
          : "column";
      return {
        "--flex-dir": flexDir,
        "--flex-dir-tablet": this.maybeApplyForTablet(flexDir),
      };
    },
    get columnCssVars() {
      const width = "100%";
      const marginLeft = "0";
      return {
        "--column-width": width,
        "--column-margin-left": marginLeft,
        "--column-width-tablet": this.maybeApplyForTablet(width),
        "--column-margin-left-tablet": this.maybeApplyForTablet(marginLeft),
      };
    },
  });

  return (
    <div
      class={css({
        display: "flex",
        alignItems: "stretch",
        lineHeight: "normal",
        "@media (max-width: 999px)": {
          flexDirection: "var(--flex-dir-tablet)",
        },
        "@media (max-width: 639px)": {
          flexDirection: "var(--flex-dir)",
        },
      })}
      style={state.columnsCssVars}
    >
      <For each={props.columns}>
        {(column, _index) => {
          const index = _index();
          return (
            <div
              class={css({
                flexGrow: "1",
                "@media (max-width: 999px)": {
                  width: "var(--column-width-tablet) !important",
                  marginLeft: "var(--column-margin-left-tablet) !important",
                },
                "@media (max-width: 639px)": {
                  width: "var(--column-width) !important",
                  marginLeft: "var(--column-margin-left) !important",
                },
              })}
              style={{
                width: state.getColumnCssWidth(index),
                "margin-left": `${index === 0 ? 0 : state.getGutterSize()}px`,
                ...state.columnCssVars,
              }}
              key={index}
            >
              <RenderBlocks blocks={column.blocks}></RenderBlocks>
            </div>
          );
        }}
      </For>
    </div>
  );
}

export default Columns;

// packages/sdks/output/react-native/src/blocks/columns/columns.lite.tsx
import * as React from "react";
import { View, StyleSheet, Image, Text } from "react-native";
import RenderBlocks from "../../components/render-blocks.lite";

export default function Columns(props) {
  function getGutterSize() {
    return typeof props.space === "number" ? props.space || 0 : 20;
  }

  function getColumns() {
    return props.columns || [];
  }

  function getWidth(index) {
    const columns = getColumns();
    return columns[index]?.width || 100 / columns.length;
  }

  function getColumnCssWidth(index) {
    const columns = getColumns();
    const gutterSize = getGutterSize();
    const subtractWidth = (gutterSize * (columns.length - 1)) / columns.length;
    return `calc(${getWidth(index)}% - ${subtractWidth}px)`;
  }

  function maybeApplyForTablet(prop) {
    const _stackColumnsAt = props.stackColumnsAt || "tablet";

    return _stackColumnsAt === "tablet" ? prop : "inherit";
  }

  function columnsCssVars() {
    const flexDir =
      props.stackColumnsAt === "never"
        ? "inherit"
        : props.reverseColumnsWhenStacked
        ? "column-reverse"
        : "column";
    return {
      "--flex-dir": flexDir,
      "--flex-dir-tablet": maybeApplyForTablet(flexDir),
    };
  }

  function columnCssVars() {
    const width = "100%";
    const marginLeft = "0";
    return {
      "--column-width": width,
      "--column-margin-left": marginLeft,
      "--column-width-tablet": maybeApplyForTablet(width),
      "--column-margin-left-tablet": maybeApplyForTablet(marginLeft),
    };
  }

  return (
    <View style={styles.view1}>
      {props.columns?.map((column, index) => (
        <View style={styles.view2} key={index}>
          <RenderBlocks blocks={column.blocks} />
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  view1: { display: "flex", alignItems: "stretch" },
  view2: { flexGrow: 1 },
});
