// packages/sdks/snippets/vue/src/views/blueprints/NavLinks.vue
<template>
    <nav>
      <h1>Acme company</h1>
      <NavBar :links="links" />
      <div class="auth-buttons">
        <button>Login</button>
        <button>Register</button>
      </div>
    </nav>
  </template>
  
  <script setup lang="ts">
  import { ref, onMounted } from 'vue';
  import { fetchOneEntry } from '@builder.io/sdk-vue';
  import type { BuilderContent } from '@builder.io/sdk-vue';
  import NavBar from '@/components/NavBar.vue';
  
  const links = ref<BuilderContent | null>(null);
  
  onMounted(async () => {
    links.value = await fetchOneEntry({
      model: 'navigation-links',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b'
    });
  });
  </script>

// packages/sdks/snippets/react/src/routes/blueprints/NavLinks.tsx
import { fetchOneEntry, type BuilderContent } from '@builder.io/sdk-react';
import { useEffect, useState } from 'react';
import NavBar from '../../components/NavBar';

export default function NavLinks() {
  const [links, setLinks] = useState<BuilderContent | null>(null);

  useEffect(() => {
    fetchOneEntry({
      model: 'navigation-links',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    }).then((data) => {
      setLinks(data);
    });
  }, []);

  return (
    <nav>
      <h1>Acme company</h1>

      {/* Navigation links from Builder */}
      {links && <NavBar links={links} />}

      <div className="auth-buttons">
        <button>Login</button>
        <button>Register</button>
      </div>
    </nav>
  );
}
