// packages/sdks/snippets/vue/src/views/blueprints/ProductEditorial.vue
<!-- src/views/ProductEditorial.vue -->
<template>
    <div v-if="!product && !editorial && !isPreviewing()">404</div>
    <div v-else>
      <ProductHeader />
      <ProductInfo :product="product" />
      <Content :model="modelName" :content="editorial" :apiKey="apiKey" /> 
      <ProductFooter />
    </div>
  </template>
  
  <script setup lang="ts">

  import { ref, onMounted } from 'vue';
  import { Content, fetchOneEntry, isPreviewing, type BuilderContent } from '@builder.io/sdk-vue';
  import ProductHeader from '@/components/product-editorial/ProductHeader.vue';
  import ProductFooter from '@/components/product-editorial/ProductFooter.vue';
  import ProductInfo from '@/components/product-editorial/ProductInfo.vue';
  import { useRoute } from 'vue-router';
  const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
  const modelName = 'product-editorial';
  
  const product = ref(null);
  const editorial = ref<BuilderContent | null>(null);
  const {params} = useRoute();

  onMounted(() => {
    function getContent() {
      fetch(`https://fakestoreapi.com/products/${params.id}`)
        .then((res) => res.json())
        .then((productData) => {
          fetchOneEntry({
            model: modelName,
            apiKey: apiKey,
            userAttributes: { urlPath: window.location.pathname },
          }).then((editorialData) => {
            product.value = productData;
            editorial.value = editorialData;
          });
        });
    }
    getContent();
  });

  </script>

// packages/sdks/snippets/react/src/routes/blueprints/ProductEditorial.tsx
import {
  BuilderContent,
  Content,
  fetchOneEntry,
  isPreviewing,
} from '@builder.io/sdk-react';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import ProductFooter from '../../components/ProductFooter';
import ProductHeader from '../../components/ProductHeader';
import ProductInfo, { type Product } from '../../components/ProductInfo';

const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
const MODEL_NAME = 'product-editorial';

export default function ProductEditorial() {
  const [product, setProduct] = useState<Product | null>(null);
  const [editorial, setEditorial] = useState<BuilderContent | null>(null);
  const { id } = useParams();

  useEffect(() => {
    fetch(`https://fakestoreapi.com/products/${id}`)
      .then((res) => res.json())
      .then((productData) => {
        setProduct(productData);
      });
  }, [id]);

  useEffect(() => {
    fetchOneEntry({
      model: MODEL_NAME,
      apiKey: API_KEY,
      userAttributes: { urlPath: window.location.pathname },
    }).then((editorialData) => {
      setEditorial(editorialData);
    });
  }, []);

  if (!isPreviewing() && !product && !editorial) return <div>404</div>;

  return (
    <>
      <ProductHeader />
      <ProductInfo product={product} />
      {/* Render Builder content below */}
      <Content model={MODEL_NAME} content={editorial} apiKey={API_KEY} />
      <ProductFooter />
    </>
  );
}
