// packages/sdks/src/blocks/button/button.lite.tsx
import { componentInfo } from './component-info';
import { Show } from '@builder.io/mitosis';
import { useMetadata } from '@builder.io/mitosis';

export interface ButtonProps {
  attributes?: any;
  text?: string;
  link?: string;
  openLinkInNewTab?: boolean;
}

export default function Button(props: ButtonProps) {
  return (
    <>
      <Show
        when={props.link}
        else={<span {...props.attributes}>{props.text}</span>}
      >
        <a
          {...props.attributes}
          role="button"
          href={props.link}
          target={props.openLinkInNewTab ? '_blank' : undefined}
        >
          {props.text}
        </a>
      </Show>
    </>
  );
}

// packages/sdks/output/solid/src/blocks/button.lite.tsx
import { Show } from "solid-js";

export default function Button(props) {
  return (
    <>
      <Show when={props.link}>
        <a
          {...props.attributes}
          role="button"
          href={props.link}
          target={props.openLinkInNewTab ? "_blank" : undefined}
        >
          {props.text}
        </a>
      </Show>
    </>
  );
}
