// packages/sdks/output/react-native/src/blocks/select.lite.tsx
import * as React from "react";
import { View, StyleSheet, Image, Text } from "react-native";
import { isEditing } from "../functions/is-editing";

export default function SelectComponent(props) {
  return (
    <View
      {...props.attributes}
      value={props.value}
      key={
        isEditing() && props.defaultValue ? props.defaultValue : "default-key"
      }
      defaultValue={props.defaultValue}
      name={props.name}
    >
      {props.options?.map((option, index) => (
        <View value={option.value}>
          <Text>{option.name || option.value}</Text>
        </View>
      ))}
    </View>
  );
}

// packages/sdks/output/solid/src/blocks/select.lite.tsx
import { For } from "solid-js";

import { isEditing } from "../functions/is-editing";

export default function SelectComponent(props) {
  return (
    <select
      {...props.attributes}
      value={props.value}
      key={
        isEditing() && props.defaultValue ? props.defaultValue : "default-key"
      }
      defaultValue={props.defaultValue}
      name={props.name}
    >
      <For each={props.options}>
        {(option, index) => (
          <option value={option.value}>{option.name || option.value}</option>
        )}
      </For>
    </select>
  );
}
