// packages/sdks/output/vue/nuxt2/src/blocks/video.vue
<template>
  <video
    v-bind="attributes"
    preload="none"
    :style="{
  width: '100%',
  height: '100%',
  ...(attributes && attributes.style),
  objectFit: fit,
  objectPosition: position,
  // Hack to get object fit to work as expected and
  // not have the video overflow
  borderRadius: 1
}"
    :key="video || 'no-src'"
    :poster="posterImage"
    :autoPlay="autoPlay"
    :muted="muted"
    :controls="controls"
    :loop="loop"
  ></video>
</template>
<script>
import { registerComponent } from "../functions/register-component";

export default registerComponent(
  {
    name: "builder-video",

    props: [
      "attributes",
      "fit",
      "position",
      "video",
      "posterImage",
      "autoPlay",
      "muted",
      "controls",
      "loop",
    ],
  },
  {
    name: "Video",
    canHaveChildren: true,
    builtIn: true,
    defaultStyles: { minHeight: "20px", minWidth: "20px" },
    image:
      "https://firebasestorage.googleapis.com/v0/b/builder-3b0a2.appspot.com/o/images%2Fbaseline-videocam-24px%20(1).svg?alt=media&token=49a84e4a-b20e-4977-a650-047f986874bb",
    inputs: [
      {
        name: "video",
        type: "file",
        allowedFileTypes: ["mp4"],
        bubble: true,
        defaultValue:
          "https://firebasestorage.googleapis.com/v0/b/builder-3b0a2.appspot.com/o/assets%2FKQlEmWDxA0coC3PK6UvkrjwkIGI2%2F28cb070609f546cdbe5efa20e931aa4b?alt=media&token=912e9551-7a7c-4dfb-86b6-3da1537d1a7f",
        required: true,
      },
      {
        name: "posterImage",
        type: "file",
        allowedFileTypes: ["jpeg", "png"],
        helperText: "Image to show before the video plays",
      },
      { name: "autoPlay", type: "boolean", defaultValue: true },
      { name: "controls", type: "boolean", defaultValue: false },
      { name: "muted", type: "boolean", defaultValue: true },
      { name: "loop", type: "boolean", defaultValue: true },
      { name: "playsInline", type: "boolean", defaultValue: true },
      {
        name: "fit",
        type: "text",
        defaultValue: "cover",
        enum: ["contain", "cover", "fill", "auto"],
      },
      {
        name: "fitContent",
        type: "boolean",
        helperText:
          "When child blocks are provided, fit to them instead of using the aspect ratio",
        defaultValue: true,
        advanced: true,
      },
      {
        name: "position",
        type: "text",
        defaultValue: "center",
        enum: [
          "center",
          "top",
          "left",
          "right",
          "bottom",
          "top left",
          "top right",
          "bottom left",
          "bottom right",
        ],
      },
      { name: "height", type: "number", advanced: true },
      { name: "width", type: "number", advanced: true },
      {
        name: "aspectRatio",
        type: "number",
        advanced: true,
        defaultValue: 0.7004048582995948,
      },
      {
        name: "lazyLoad",
        type: "boolean",
        helperText:
          'Load this video "lazily" - as in only when a user scrolls near the video. Recommended for optmized performance and bandwidth consumption',
        defaultValue: true,
        advanced: true,
      },
    ],
  }
);
</script>

// packages/sdks/output/solid/src/blocks/video.jsx
function Video(props) {
  return <video {...props.attributes} preload="none" style={{
    width: "100%",
    height: "100%",
    ...props.attributes?.style,
    "object-fit": props.fit,
    "object-position": props.position,
    // Hack to get object fit to work as expected and
    // not have the video overflow
    "border-radius": 1
  }} key={props.video || "no-src"} poster={props.posterImage} autoPlay={props.autoPlay} muted={props.muted} controls={props.controls} loop={props.loop}></video>;
}

export default Video;import { registerComponent } from '../functions/register-component';
registerComponent(Video, {name:'Video',canHaveChildren:true,builtIn:true,defaultStyles:{minHeight:'20px',minWidth:'20px'},image:'https://firebasestorage.googleapis.com/v0/b/builder-3b0a2.appspot.com/o/images%2Fbaseline-videocam-24px%20(1).svg?alt=media&token=49a84e4a-b20e-4977-a650-047f986874bb',inputs:[{name:'video',type:'file',allowedFileTypes:['mp4'],bubble:true,defaultValue:'https://firebasestorage.googleapis.com/v0/b/builder-3b0a2.appspot.com/o/assets%2FKQlEmWDxA0coC3PK6UvkrjwkIGI2%2F28cb070609f546cdbe5efa20e931aa4b?alt=media&token=912e9551-7a7c-4dfb-86b6-3da1537d1a7f',required:true},{name:'posterImage',type:'file',allowedFileTypes:['jpeg','png'],helperText:'Image to show before the video plays'},{name:'autoPlay',type:'boolean',defaultValue:true},{name:'controls',type:'boolean',defaultValue:false},{name:'muted',type:'boolean',defaultValue:true},{name:'loop',type:'boolean',defaultValue:true},{name:'playsInline',type:'boolean',defaultValue:true},{name:'fit',type:'text',defaultValue:'cover',enum:['contain','cover','fill','auto']},{name:'fitContent',type:'boolean',helperText:'When child blocks are provided, fit to them instead of using the aspect ratio',defaultValue:true,advanced:true},{name:'position',type:'text',defaultValue:'center',enum:['center','top','left','right','bottom','top left','top right','bottom left','bottom right']},{name:'height',type:'number',advanced:true},{name:'width',type:'number',advanced:true},{name:'aspectRatio',type:'number',advanced:true,defaultValue:0.7004048582995948},{name:'lazyLoad',type:'boolean',helperText:'Load this video "lazily" - as in only when a user scrolls near the video. Recommended for optmized performance and bandwidth consumption',defaultValue:true,advanced:true}]});
