// packages/sdks/output/svelte/src/components/render-blocks.svelte
<script>
    
    
    
    
  import  {  isEditing  }  from '../functions/is-editing.js';
import  BlockStyles,  {  }  from './render-block/block-styles.svelte';
import  RenderBlock,  {  }  from './render-block/render-block.svelte';

  

    

    
    export let blocks;
export let parent;
export let path;
    
    function onClick() {
if (isEditing() && !blocks?.length) {
  window.parent?.postMessage({
    type: 'builder.clickEmptyBlocks',
    data: {
      parentElementId: parent,
      dataPath: path
    }
  }, '*');
}
}

function onMouseEnter() {
if (isEditing() && !blocks?.length) {
  window.parent?.postMessage({
    type: 'builder.hoverEmptyBlocks',
    data: {
      parentElementId: parent,
      dataPath: path
    }
  }, '*');
}
}
    $: className = () => {
return 'builder-blocks' + (!blocks?.length ? ' no-blocks' : '');
};

    
    
    

    

    

    
  </script>

  <div    builder-path={path}  builder-parent-id={parent}  dataSet={{
class: className()
}}  on:click="{event => onClick()}"  on:mouseenter="{event => onMouseEnter()}"  class={className()} >
    

    

{#if blocks }

      

{#each blocks as block, index }
<RenderBlock  key={'render-block-' + block.id}  block={block} ></RenderBlock>
{/each}


    


{/if}

    

{#if blocks }

      

{#each blocks as block, index }
<BlockStyles  key={'block-style-' + block.id}  block={block} ></BlockStyles>
{/each}


    


{/if}

  </div>

  <style>
    .div { 
display: flex;
flex-direction: column;
align-items: stretch; }
  </style>

// examples/next-app-dir/src/sdk-src/components/render-blocks.tsx
'use client'
import * as React from 'react'
import { useContext } from 'react'

export type RenderBlockProps = {
  blocks?: BuilderBlock[]
  parent?: string
  path?: string
  styleProp?: Record<string, any>
}
import BuilderContext from '../context/builder.context.js'
import { isEditing } from '../functions/is-editing.js'
import type { BuilderBlock } from '../types/builder-block.js'
import BlockStyles from './render-block/block-styles'
import RenderBlock from './render-block/render-block'

function RenderBlocks(props: RenderBlockProps) {
  function className() {
    return 'builder-blocks' + (!props.blocks?.length ? ' no-blocks' : '')
  }

  function onClick() {
    if (isEditing() && !props.blocks?.length) {
      window.parent?.postMessage(
        {
          type: 'builder.clickEmptyBlocks',
          data: {
            parentElementId: props.parent,
            dataPath: props.path,
          },
        },
        '*'
      )
    }
  }

  function onMouseEnter() {
    if (isEditing() && !props.blocks?.length) {
      window.parent?.postMessage(
        {
          type: 'builder.hoverEmptyBlocks',
          data: {
            parentElementId: props.parent,
            dataPath: props.path,
          },
        },
        '*'
      )
    }
  }

  const builderContext = useContext(BuilderContext)

  return (
    <>
      <div
        className={className() + ' div-6dd9939e'}
        builder-path={props.path}
        builder-parent-id={props.parent}
        style={props.styleProp}
        onClick={(event) => onClick()}
        onMouseEnter={(event) => onMouseEnter()}
        onKeyPress={(event) => onClick()}
      >
        {props.blocks ? (
          <>
            {props.blocks?.map((block) => (
              <RenderBlock
                key={'render-block-' + block.id}
                block={block}
                context={builderContext}
              />
            ))}
          </>
        ) : null}

        {props.blocks ? (
          <>
            {props.blocks?.map((block) => (
              <BlockStyles
                key={'block-style-' + block.id}
                block={block}
                context={builderContext}
              />
            ))}
          </>
        ) : null}
      </div>

      <style>{`.div-6dd9939e {
  display: flex;
  flex-direction: column;
  align-items: stretch;
}`}</style>
    </>
  )
}

export default RenderBlocks
