// packages/sdks/output/solid/src/blocks/image.lite.tsx
import { Show } from "solid-js";

import { css } from "solid-styled-components";

export default function Image(props) {
  return (
    <div
      class={css({
        position: "relative",
      })}
    >
      <picture>
        <img
          class={
            "builder-image" +
            (props.class ? " " + props.class : "") +
            " " +
            css({
              opacity: "1",
              transition: "opacity 0.2s ease-in-out",
              position: "absolute",
              height: "100%",
              width: "100%",
              top: "0px",
              left: "0px",
            })
          }
          loading="lazy"
          alt={props.altText}
          aria-role={props.altText ? "presentation" : undefined}
          style={{
            "object-position": props.backgroundSize || "center",
            "object-fit": props.backgroundSize || "cover",
          }}
          src={props.image}
          srcset={props.srcset}
          sizes={props.sizes}
        />
        <source srcSet={props.srcset} />
      </picture>
      <Show
        when={
          props.aspectRatio &&
          !(props.fitContent && props.builderBlock?.children?.length)
        }
      >
        <div
          class={css({
            width: "100%",
            pointerEvents: "none",
            fontSize: "0",
          })}
          style={{
            "padding-top": props.aspectRatio * 100 + "%",
          }}
        >
          {" "}
        </div>
      </Show>
      <Show when={props.builderBlock?.children?.length && props.fitContent}>
        {props.children}
      </Show>
      <Show when={!props.fitContent}>
        <div
          class={css({
            display: "flex",
            flexDirection: "column",
            alignItems: "stretch",
            position: "absolute",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
          })}
        >
          {props.children}
        </div>
      </Show>
    </div>
  );
}

// packages/sdks/output/react-native/src/blocks/image/image.lite.tsx
import * as React from "react";
import { View, StyleSheet, Image, Text } from "react-native";

export default function Image(props) {
  return (
    <View style={styles.view1}>
      <View>
        <View
          loading="lazy"
          alt={props.altText}
          aria-role={props.altText ? "presentation" : undefined}
          style={styles.view2}
          src={props.image}
          srcset={props.srcset}
          sizes={props.sizes}
        />

        <View srcSet={props.srcset} />
      </View>

      <>
        {props.aspectRatio &&
        !(props.fitContent && props.builderBlock?.children?.length) ? (
          <View style={styles.view3}>
            <Text> </Text>
          </View>
        ) : null}
      </>

      <>
        {props.builderBlock?.children?.length && props.fitContent ? (
          <>
            <Text>{props.children}</Text>
          </>
        ) : null}
      </>

      <>
        {!props.fitContent ? (
          <>
            <View style={styles.view4}>
              <Text>{props.children}</Text>
            </View>
          </>
        ) : null}
      </>
    </View>
  );
}

const styles = StyleSheet.create({
  view1: { position: "relative" },
  view2: {
    opacity: 1,
    transition: "opacity 0.2s ease-in-out",
    position: "absolute",
    height: 100,
    width: 100,
    top: 0,
    left: 0,
  },
  view3: { width: 100, pointerEvents: "none", fontSize: 0 },
  view4: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    position: "absolute",
    top: 0,
    left: 0,
    width: 100,
    height: 100,
  },
});
