// packages/sdks/snippets/svelte/src/components/custom-child/CustomChild.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-svelte';
  import type { BuilderContent } from '@builder.io/sdk-svelte';
  import { customHeroInfo } from './CustomHeroInfo';

  let loading = true;
  let content: BuilderContent | null;

  let model = 'custom-child';
  let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  onMount(() => {
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    }).then((data) => {
      content = data;
      loading = false;
    });
  });
</script>

{#if loading}
  <div>Loading...</div>
{:else if !content && !isPreviewing()}
  <div>404 - Not Found</div>
{:else}
  <Content {content} {apiKey} {model} customComponents={[customHeroInfo]} />
{/if}

// packages/sdks/snippets/angular-17/src/app/custom-child/custom-child.component.ts
import { Component, type OnInit } from '@angular/core';
import {
  Content,
  fetchOneEntry,
  type BuilderContent,
} from '@builder.io/sdk-angular';
import { customHeroInfo } from './custom-hero/custom-hero.component';

@Component({
  selector: 'app-custom-child',
  standalone: true,
  imports: [Content],
  template: `
    @if (content) {
      <div>
        <builder-content
          [content]="content"
          [model]="model"
          [apiKey]="apiKey"
          [customComponents]="[customHeroInfo]"
        ></builder-content>
      </div>
    }

    @if (notFound) {
      <div>404 Not Found</div>
    }
  `,
})
export class CustomChildComponent implements OnInit {
  notFound = false;
  content: BuilderContent | null = null;
  customHeroInfo = customHeroInfo;
  model = 'page';
  apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  async ngOnInit() {
    this.content = await fetchOneEntry({
      model: this.model,
      apiKey: this.apiKey,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    });

    if (!this.content) {
      this.notFound = true;
    }
  }
}
