// packages/sdks/integration/frameworks/vue/src/App.vue
<template>
  <div>
    <RenderContent model="page" :content="content" />
  </div>
</template>

<script>
import { RenderContent } from '@builder.io/sdk-vue';

// TODO: .d.ts compilation for the JSX Lite SDK code
const content = {
  data: {
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        responsiveStyles: {
          large: {
            padding: '20px',
            backgroundColor: 'red',
            color: 'white',
          },
        },
        component: {
          name: 'Text',
          options: {
            text: 'Hi there',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        responsiveStyles: {
          large: {
            margin: '10px',
            padding: '20px',
            backgroundColor: 'white',
          },
        },
        component: {
          name: 'Text',
          options: {
            text: 'Hello',
          },
        },
      },
    ],
  },
};

export default {
  name: 'App',
  data: () => ({ content }),
  components: {
    RenderContent,
  },
};
</script>

// examples/react-native/App.jsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { RenderContent, registerComponent } from '@builder.io/sdk-react-native';

// You can fetch this content in your code via our Content APIs
// https://builder.io/c/docs/query-api
const content = {
  data: {
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        responsiveStyles: {
          large: {
            padding: '20px',
            backgroundColor: 'steelblue',
            color: 'white',
          },
        },
        component: {
          name: 'Text',
          options: {
            text: 'Hi there',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        responsiveStyles: {
          large: {
            margin: '10px',
            padding: '20px',
            backgroundColor: 'white',
            color: 'white',
          },
        },
        component: {
          name: 'Text',
          options: {
            text: 'Hello',
          },
        },
      },
    ],
  },
};

function CustomComponent(props: { text: string }) {
  return (
    <>
      <Text>I am a custom comopnent!</Text>
      <Text>{props.text}</Text>
    </>
  );
}

registerComponent(CustomComponent, {
  name: 'Custom Component',
  inputs: [{ name: 'text', type: 'string' }],
});

export default function App() {
  return (
    <View style={styles.container}>
      <RenderContent model="page" content={content} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: '20px',
  },
});
