// packages/sdks/output/svelte/src/blocks/select.svelte
<script>
  import { isEditing } from "../functions/is-editing";

  export let attributes;
  export let value;
  export let defaultValue;
  export let name;
  export let options;

</script>

<select
  {...attributes}
  {value}
  key={isEditing() && defaultValue ? defaultValue : 'default-key'}
  {defaultValue}
  {name}>
  {#each options as option}
    <option value={option.value}>{option.name || option.value}</option>
  {/each}
</select>

// examples/next-app-dir/src/sdk-src/blocks/select/select.tsx
'use client'
import * as React from 'react'

export interface FormSelectProps {
  options?: {
    name?: string
    value: string
  }[]
  attributes?: any
  name?: string
  value?: string
  defaultValue?: string
}

import { isEditing } from '../../functions/is-editing.js'

function SelectComponent(props: FormSelectProps) {
  return (
    <select
      {...props.attributes}
      value={props.value}
      key={
        isEditing() && props.defaultValue ? props.defaultValue : 'default-key'
      }
      defaultValue={props.defaultValue}
      name={props.name}
    >
      {props.options?.map((option) => (
        <option value={option.value}>{option.name || option.value}</option>
      ))}
    </select>
  )
}

export default SelectComponent
