// packages/sdks/output/solid/src/blocks/button/button.jsx
import { Show } from "solid-js";

function Button(props) {
  return <>
      <Show when={props.link}>
        <a {...props.attributes} role="button" href={props.link} target={props.openLinkInNewTab ? "_blank" : undefined}>
          {props.text}
        </a>
      </Show>
    </>;
}

export default Button;

// packages/sdks/output/svelte/src/blocks/button/button.svelte
<script>
  
  
  
  



  

  
  export let attributes;
export let text;
export let link;
export let openLinkInNewTab;
  
  
  

  
  
  

  

  

  
</script>


  

{#if link }

    
<a {...attributes} role="button"  href={link}  target={openLinkInNewTab ? '_blank' : undefined} >
      
{text}

    </a>

  
{/if}
