// packages/sdks/snippets/react/src/routes/blueprints/homepage.tsx
import {
  BuilderContent,
  Content,
  fetchOneEntry,
  isPreviewing,
} from '@builder.io/sdk-react';
import { useEffect, useState } from 'react';

export default function Homepage() {
  const [content, setContent] = useState<BuilderContent | null>(null);

  useEffect(() => {
    fetchOneEntry({
      model: 'homepage',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    }).then((content) => setContent(content));
  }, []);

  if (!content && !isPreviewing()) {
    return <div>404</div>;
  }

  return (
    <Content
      apiKey="ee9f13b4981e489a9a1209887695ef2b"
      model="homepage"
      content={content}
    />
  );
}

// packages/sdks/snippets/svelte/src/components/blueprints/Homepage.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    fetchOneEntry,
    Content,
    type BuilderContent,
    isPreviewing,
  } from '@builder.io/sdk-svelte';

  let content: BuilderContent | null = null;

  onMount(() => {
    fetchOneEntry({
      model: 'homepage',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    }).then((res) => {
      content = res;
    });
  });
</script>

{#if !content && !isPreviewing()}
  <div>404</div>
{:else}
  <Content
    model="homepage"
    {content}
    apiKey="ee9f13b4981e489a9a1209887695ef2b"
  />
{/if}
