// packages/sdks/snippets/hydrogen/app/components/CustomHero.tsx
// app/components/CustomHero.tsx
import React from 'react';
import type {RegisteredComponent} from '@builder.io/sdk-react';

export function CustomHero({children}: {children?: React.ReactNode}) {
  return (
    <>
      <div>This is text from your component</div>
      {children}
    </>
  );
}

export const customHeroInfo: RegisteredComponent = {
  name: 'CustomHero',
  component: CustomHero,
  canHaveChildren: true,
  defaultChildren: [
    {
      '@type': '@builder.io/sdk:Element',
      component: {
        name: 'Text',
        options: {text: 'This is Builder text'},
      },
    },
  ],
};

// packages/sdks/snippets/angular-17-ssr/src/app/custom-child/custom-hero/custom-hero.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import type { RegisteredComponent } from '@builder.io/sdk-angular';

@Component({
  selector: 'app-custom-hero',
  standalone: true,
  imports: [CommonModule],
  template: ` <div>This is text from your component</div> `,
})
export class CustomHeroComponent {}

export const customHeroInfo: RegisteredComponent = {
  component: CustomHeroComponent,
  name: 'CustomHero',
  canHaveChildren: true,
  defaultChildren: [
    {
      '@type': '@builder.io/sdk:Element',
      component: {
        name: 'Text',
        options: {
          text: 'This is Builder text',
        },
      },
    },
  ],
};
