// packages/sdks/snippets/qwik-city/src/components/CustomHero.tsx
import { component$, Slot } from '@builder.io/qwik';
import type { RegisteredComponent } from '@builder.io/sdk-qwik';

export const CustomHero = component$(() => {
  return (
    <>
      <div>This is text from your component</div>
      <Slot />
    </>
  );
});

export const customHeroInfo: RegisteredComponent = {
  component: CustomHero,
  name: 'CustomHero',
  inputs: [],
  canHaveChildren: true,
  defaultChildren: [
    {
      '@type': '@builder.io/sdk:Element',
      component: {
        name: 'Text',
        options: {
          text: 'This is Builder text',
        },
      },
    },
  ],
};

// packages/sdks/snippets/react-sdk-next-14-app/app/components/CustomHero.tsx
'use client';

import type { RegisteredComponent } from '@builder.io/sdk-react';
import React from 'react';

const CustomHero = ({ children }: { children?: React.ReactNode }) => {
  return (
    <>
      <div>This is text from your component</div>
      {children}
    </>
  );
};

export const customHeroInfo: RegisteredComponent = {
  name: 'CustomHero',
  component: CustomHero,
  canHaveChildren: true,
  defaultChildren: [
    {
      '@type': '@builder.io/sdk:Element',
      component: {
        name: 'Text',
        options: {
          text: 'This is Builder text',
        },
      },
    },
  ],
};
