// packages/sdks/snippets/svelte/src/components/blueprints/Hero.svelte
<!-- Hero.svelte -->
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    fetchOneEntry,
    Content,
    type BuilderContent,
  } from '@builder.io/sdk-svelte';
  let productHero: BuilderContent | null = null;

  onMount(() => {
    fetchOneEntry({
      model: 'collection-hero',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      userAttributes: { urlPath: window.location.pathname },
    }).then((data) => {
      productHero = data;
    });
  });
</script>

<!-- Your nav goes here -->
<!-- Hero Section -->
{#if productHero}
  <Content
    model="collection-hero"
    content={productHero}
    apiKey="ee9f13b4981e489a9a1209887695ef2b"
  />
{/if}
<!-- The rest of your page goes here -->

// packages/sdks/snippets/angular-16/src/app/hero/hero.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import {
  Content,
  fetchOneEntry,
  type BuilderContent,
} from '@builder.io/sdk-angular';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [Content, CommonModule],
  template: `
    <!-- Your nav goes here -->
    <!-- Hero Section -->
    <div *ngIf="productHero">
      <builder-content
        [model]="'collection-hero'"
        [content]="productHero"
        [apiKey]="'ee9f13b4981e489a9a1209887695ef2b'"
      ></builder-content>
    </div>
    <!-- The rest of your page goes here -->
  `,
})
export class HeroComponent {
  productHero: BuilderContent | null = null;

  async ngOnInit() {
    this.productHero = await fetchOneEntry({
      model: 'collection-hero',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      userAttributes: {
        urlPath: window.location.pathname,
      },
    });
  }
}
