// packages/sdks/output/svelte/src/blocks/symbol.lite.tsx
<script>
  import { onMount } from "svelte";
  import { afterUpdate } from "svelte";

  import RenderContent from "../components/render-content.lite";
  import BuilderContext from "../context/builder.context.lite";
  import { getContent } from "../functions/get-content";

  export let attributes;
  export let symbol;

  let className = "builder-symbol";
  let content = null;

  onMount(() => {
    content = symbol?.content;
  });

  afterUpdate(() => {
    const symbol = symbol;

    if (symbol && !symbol.content && !content && symbol.model) {
      getContent({
        model: symbol.model,
        apiKey: builderContext.apiKey!,
        options: {
          entry: symbol.entry,
        },
      }).then((response) => {
        content = response;
      });
    }
  });

</script>

<div
  {...attributes}
  dataSet={{ class: className }}
  class={className}>
  <RenderContent
    apiKey={builderContext.apiKey}
    context={builderContext.context}
    data={{ ...symbol?.data, ...builderContext.state, ...symbol?.content?.data?.state }}
    model={symbol?.model}
    {content} />
</div>

// packages/sdks/output/solid/src/blocks/symbol/symbol.lite.tsx
import { createMutable } from "solid-js/store";

import RenderContent from "../../components/render-content/render-content.lite";
import BuilderContext from "../../context/builder.context";
import { getContent } from "../../functions/get-content";

function Symbol(props) {
  const state = createMutable({ className: "builder-symbol", content: null });

  const builderContext = useContext(BuilderContext);

  onMount(() => {
    state.content = props.symbol?.content;
  });

  return (
    <div
      class={state.className}
      {...props.attributes}
      dataSet={{
        class: state.className,
      }}
    >
      <RenderContent
        apiKey={builderContext.apiKey}
        context={builderContext.context}
        data={{
          ...props.symbol?.data,
          ...builderContext.state,
          ...props.symbol?.state.content?.data?.state,
        }}
        model={props.symbol?.model}
        content={state.content}
      ></RenderContent>
    </div>
  );
}

export default Symbol;
