// packages/sdks/snippets/sveltekit/src/routes/editable-region/CustomColumns.svelte
<script lang="ts">
  import { Blocks, type BuilderBlock } from '@builder.io/sdk-svelte';

  export let leftContent: BuilderBlock[];
  export let rightContent: BuilderBlock[];
  export let builderBlock: BuilderBlock;
</script>

<!-- Left Column -->
<Blocks parent={builderBlock.id} path="leftContent" blocks={leftContent} />

<!-- Right Column -->
<Blocks parent={builderBlock.id} path="rightContent" blocks={rightContent} />

// packages/sdks/snippets/vue/src/components/custom-components/custom-columns/CustomColumns.vue
<template>
  <!-- Left Column -->
    <Blocks
      :parent="builderBlock.id"
      :path="'leftContent'"
      :blocks="leftContent"
    />
  <!-- Right Column -->
    <Blocks
      :parent="builderBlock.id"
      :path="'rightContent'"
      :blocks="rightContent"
    />
</template>
  
<script setup lang="ts">
import { Blocks, type BuilderBlock } from '@builder.io/sdk-vue';

const { leftContent, rightContent, builderBlock } = defineProps<{
  leftContent: BuilderBlock[];
  rightContent: BuilderBlock[];
  builderBlock: BuilderBlock;
}>();
</script>
