// examples/vue/nuxt-3/sdk-src/blocks/video/video.vue
<template>
  <video
    :style="{
      width: '100%',
      height: '100%',
      ...attributes?.style,
      objectFit: fit,
      objectPosition: position,
      // Hack to get object fit to work as expected and
      // not have the video overflow
      borderRadius: 1,
    }"
    :src="video || 'no-src'"
    :poster="posterImage"
    v-bind="spreadProps"
  ></video>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export interface VideoProps {
  attributes?: any;
  video?: string;
  autoPlay?: boolean;
  controls?: boolean;
  muted?: boolean;
  loop?: boolean;
  playsInline?: boolean;
  aspectRatio?: number;
  width?: number;
  height?: number;
  fit?: "contain" | "cover" | "fill";
  position?:
    | "center"
    | "top"
    | "left"
    | "right"
    | "bottom"
    | "top left"
    | "top right"
    | "bottom left"
    | "bottom right";
  posterImage?: string;
  lazyLoad?: boolean;
}

export default defineComponent({
  name: "builder-video",

  props: [
    "autoPlay",
    "muted",
    "controls",
    "loop",
    "playsInline",
    "attributes",
    "fit",
    "position",
    "video",
    "posterImage",
  ],

  computed: {
    videoProps() {
      return {
        ...(this.autoPlay === true
          ? {
              autoPlay: true,
            }
          : {}),
        ...(this.muted === true
          ? {
              muted: true,
            }
          : {}),
        ...(this.controls === true
          ? {
              controls: true,
            }
          : {}),
        ...(this.loop === true
          ? {
              loop: true,
            }
          : {}),
        ...(this.playsInline === true
          ? {
              playsInline: true,
            }
          : {}),
      };
    },
    spreadProps() {
      return {
        ...this.attributes,
        ...this.videoProps,
      };
    },
  },
});
</script>

// examples/react-v2/src/sdk-src/blocks/video/video.tsx
import * as React from "react";
import type { VideoProps } from "./video.types.js";

function Video(props: VideoProps) {
  function videoProps() {
    return {
      ...(props.autoPlay === true
        ? {
            autoPlay: true,
          }
        : {}),
      ...(props.muted === true
        ? {
            muted: true,
          }
        : {}),
      ...(props.controls === true
        ? {
            controls: true,
          }
        : {}),
      ...(props.loop === true
        ? {
            loop: true,
          }
        : {}),
      ...(props.playsInline === true
        ? {
            playsInline: true,
          }
        : {}),
    };
  }

  function spreadProps() {
    return {
      ...videoProps(),
    };
  }

  return (
    <div
      style={{
        position: "relative",
      }}
    >
      <video
        className="builder-video"
        {...spreadProps()}
        preload={props.preload || "metadata"}
        style={{
          width: "100%",
          height: "100%",
          ...props.attributes?.style,
          objectFit: props.fit,
          objectPosition: props.position,
          // Hack to get object fit to work as expected and
          // not have the video overflow
          zIndex: 2,
          borderRadius: "1px",
          ...(props.aspectRatio
            ? {
                position: "absolute",
              }
            : null),
        }}
        src={props.video || "no-src"}
        poster={props.posterImage}
      >
        {!props.lazyLoad ? <source type="video/mp4" src={props.video} /> : null}
      </video>

      {props.aspectRatio &&
      !(props.fitContent && props.builderBlock?.children?.length) ? (
        <>
          <div
            style={{
              width: "100%",
              paddingTop: props.aspectRatio! * 100 + "%",
              pointerEvents: "none",
              fontSize: "0px",
            }}
          />
        </>
      ) : null}

      {props.builderBlock?.children?.length && props.fitContent ? (
        <>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "stretch",
            }}
          >
            {props.children}
          </div>
        </>
      ) : null}

      {props.builderBlock?.children?.length && !props.fitContent ? (
        <>
          <div
            style={{
              pointerEvents: "none",
              display: "flex",
              flexDirection: "column",
              alignItems: "stretch",
              position: "absolute",
              top: "0",
              left: "0",
              width: "100%",
              height: "100%",
            }}
          >
            {props.children}
          </div>
        </>
      ) : null}
    </div>
  );
}

export default Video;
