// packages/sdks/snippets/sveltekit/src/routes/advanced-child/+page.svelte
<script lang="ts">
  import { Content, isPreviewing } from '@builder.io/sdk-svelte';
  import type { PageData } from './$types';
  import { CustomTabsInfo } from './CustomTabsInfo';

  export let data: PageData;
</script>

{#if !data.data && !isPreviewing()}
  <div>404 - Not Found</div>
{:else}
  <Content
    content={data.data}
    apiKey="ee9f13b4981e489a9a1209887695ef2b"
    model="advanced-child"
    customComponents={[CustomTabsInfo]}
  />
{/if}

// packages/sdks/snippets/nuxt/pages/advanced-child.vue
<script setup lang="ts">
  import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-vue';
  import CustomTabsInfo from '../components/CustomTabsInfo';

  const route = useRoute();
  const model = 'advanced-child';
  const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  const { data: content, pending } = await useAsyncData(
    `builder-${model}-${route.path}`,
    () => fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
          urlPath: route.path,
        },
      })
    );
    </script>

<template>
  <div>
    <div v-if="pending">Loading...</div>
    <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
    <Content
      v-else
      :content="content"
      :model="model"
      :apiKey="apiKey"
      :customComponents="[CustomTabsInfo]"
    />
  </div>
</template>
