// packages/sdks/snippets/sveltekit/src/routes/home/+page.svelte
<script lang="ts">
  import { Content, isPreviewing } from '@builder.io/sdk-svelte';
  import type { PageData } from './$types';
  export let data: PageData;
</script>

{#if !data.content && !isPreviewing()}
  <div>404</div>
{:else}
  <Content
    model="homepage"
    content={data.content}
    apiKey="ee9f13b4981e489a9a1209887695ef2b"
  />
{/if}

// packages/sdks/snippets/nuxt/pages/home.vue
<script setup lang="ts">
import { useAsyncData } from '#app';
import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-vue';

const model = 'homepage';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const { data: content } = await useAsyncData('homepage', () =>
  fetchOneEntry({
    model: model,
    apiKey: apiKey,
  })
);
</script>

<template>
  <div v-if="content || isPreviewing()">
    <Content :model="model" :content="content" :apiKey="apiKey" />
  </div>
  <div v-else>404</div>
</template>
