// packages/sdks/snippets/react-sdk-next-14-app/app/(blueprints-product-details)/products/[handle]/page.tsx
// app/product-editorial/[handle]/page.tsx
import { ProductFooter } from '@/app/components/ProductFooter';
import { ProductHeader } from '@/app/components/ProductHeader';
import { ProductInfo, type Product } from '@/app/components/ProductInfo';
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type BuilderContent,
} from '@builder.io/sdk-react';

const MODEL_NAME = 'product-editorial';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export default async function ProductEditorialPage({
  params,
}: {
  params: { handle: string };
}) {
  const editorialContent: BuilderContent | null = await fetchOneEntry({
    model: MODEL_NAME,
    apiKey: API_KEY,
    userAttributes: { urlPath: `/products/${params.handle}` },
  });

  const productRes = await fetch(
    `https://fakestoreapi.com/products/${params.handle}`
  );
  const product: Product = await productRes.json();

  if (!editorialContent && !product && !isPreviewing()) {
    return <div>404</div>;
  }

  return (
    <div className="content">
      <ProductHeader />
      <ProductInfo product={product} />
      <Content model={MODEL_NAME} content={editorialContent} apiKey={API_KEY} />
      <ProductFooter />
    </div>
  );
}

// packages/sdks/snippets/qwik-city/src/routes/products/[handle]/index.tsx
import { component$ } from '@builder.io/qwik';
import { routeLoader$ } from '@builder.io/qwik-city';
import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-qwik';

import ProductFooter from '~/components/ProductFooter';
import ProductHeader from '~/components/ProductHeader';
import { ProductInfo, type Product } from '~/components/ProductInfo';

const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
const MODEL_NAME = 'product-editorial';

export const useEditorial = routeLoader$(async ({ params }) => {
  return fetchOneEntry({
    model: MODEL_NAME,
    apiKey: API_KEY,
    userAttributes: { urlPath: params.pathname },
  });
});

export const useProductData = routeLoader$(async ({ params }) => {
  return fetch(`https://fakestoreapi.com/products/${params.handle}`).then(
    (res) => res.json() as Promise<Product>
  );
});

export default component$(() => {
  const editorial = useEditorial();
  const productData = useProductData();

  if (!isPreviewing() && !editorial.value && !productData.value) {
    return <div>404</div>;
  }

  return (
    <>
      <ProductHeader />
      <ProductInfo product={productData.value} />
      <Content model={MODEL_NAME} content={editorial.value} apiKey={API_KEY} />
      <ProductFooter />
    </>
  );
});
