// packages/sdks/snippets/svelte/src/App.svelte
<!-- Quickstart snippet -->
<!-- snippets/svelte/src/App.svelte -->

<script lang="ts">
  import { Content, fetchOneEntry, type BuilderContent } from '@builder.io/sdk-svelte';

  let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
  let model = 'page';

  let content: BuilderContent | null = null;

  async function fetchContent() {
    content = await fetchOneEntry({
      apiKey,
      model,
      userAttributes: {
        urlPath: window.location.pathname
      }
    });
  }

  fetchContent();
</script>

<svelte:head>
  <title>Home</title>
</svelte:head>

<main>
  {#if content}
    <Content content={content} apiKey={apiKey} model={model}  />
  {:else}
    Content Not Found
  {/if}
</main>

// packages/sdks/snippets/solidjs/src/App.tsx
/**
 * Quickstart snippet
 * snippets/solidjs/src/App.tsx
 */
import {
  Content,
  fetchOneEntry,
  type BuilderContent,
} from '@builder.io/sdk-solid';
import { createEffect, createSignal } from 'solid-js';

const BUILDER_API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

function App() {
  const [content, setContent] = createSignal<BuilderContent | null>(null);

  createEffect(() => {
    fetchOneEntry({
      model: 'page',
      apiKey: BUILDER_API_KEY,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    }).then((data: any) => {
      setContent(data);
    });
  });

  return (
    <>
      {content() ? (
        <Content content={content()} apiKey={BUILDER_API_KEY} model="page" />
      ) : (
        <div>Not found</div>
      )}
    </>
  );
}

export default App;
