// packages/sdks/snippets/react/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import App from './App.tsx';
import AnnouncementBar from './components/AnnouncementBar.tsx';



const router = createBrowserRouter([
  {
    path: '/announcements/:id',
    element: <AnnouncementBar />,
  },
  {
    path: '/*',
    element: <App />,
  },
]);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);

// packages/sdks/snippets/solidjs/src/index.tsx
import { Router } from '@solidjs/router';
import { render } from 'solid-js/web';

const root = document.getElementById('root');

import App from './App';
import AnnouncementBar from './components/AnnouncementBar';

const routes = [
  {
    path: '/announcements/:id',
    component: AnnouncementBar,
  },
  {
    path: '*',
    component: App,
  },
];

render(() => <Router explicitLinks>{routes}</Router>, root!);
