// packages/sdks/snippets/vue/src/components/NavBar.vue
<template>
    <ul v-if="links.data?.links">
      <li v-for="(link, index) in links.data.links" :key="index">
        <a :href="link.url">{{ link.text }}</a>
      </li>
    </ul>
  </template>
  
  <script setup lang="ts">
  import type { BuilderContent } from '@builder.io/sdk-vue';
  const props = defineProps<{ links: BuilderContent }>();
  </script>

// packages/sdks/snippets/hydrogen/app/components/NavBar.tsx
import {type BuilderContent} from '@builder.io/sdk-react';

export function NavBar({links}: {links: BuilderContent | null}) {
  if (!links?.data?.links) return null;
  return (
    <ul>
      {links.data.links.map(
        (link: {url: string; text: string}, index: number) => (
          <li key={index}>
            <a href={link.url}>{link.text}</a>
          </li>
        ),
      )}
    </ul>
  );
}
