// packages/sdks/snippets/svelte/src/components/AnnouncementBar.svelte
<!-- https://www.builder.io/c/docs/integrate-section-building -->
<!-- https://www.builder.io/c/blueprints/announcement-bar -->
<!-- src/components/AnnouncementBar.svelte -->

<script lang="ts">
  import {
    Content,
    fetchOneEntry,
    type BuilderContent,
    isPreviewing,
  } from '@builder.io/sdk-svelte';

  let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
  let model = 'announcement-bar';

  let announcementBar: BuilderContent | null = null;
  let canShowContent = false;

  async function fetchContent() {
    announcementBar = await fetchOneEntry({
      apiKey,
      model,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    });
    canShowContent = announcementBar ? true : isPreviewing();
  }

  fetchContent();
</script>

<main>
  {#if canShowContent}
    <Content content={announcementBar} {apiKey} {model} />
  {/if}

  <!-- Your content coming from your app (or also Builder) -->
  <div>The rest of your page goes here</div>
</main>

// packages/sdks/snippets/vue/src/views/AnnouncementBar.vue
<!-- https://www.builder.io/c/docs/integrate-section-building -->
<!-- https://www.builder.io/c/blueprints/announcement-bar -->

<script setup lang="ts">
import {
  Content,
  type BuilderContent,
  fetchOneEntry,
  isPreviewing,
} from '@builder.io/sdk-vue';
import { onMounted, ref } from 'vue';

const content = ref<BuilderContent | null>(null);
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
const canShowContent = ref(false);
const model = 'announcement-bar';

onMounted(async () => {
  content.value = await fetchOneEntry({
    model,
    apiKey,
    userAttributes: {
      urlPath: window.location.pathname,
    },
  });
  canShowContent.value = content.value ? true : isPreviewing();
});
</script>

<template>
  <Content
    v-if="canShowContent"
    :model="model"
    :content="content"
    :api-key="apiKey"
  />

  <!-- Your content coming from your app (or also Builder) -->
  <div>The rest of your page goes here</div>
</template>
