// packages/sdks/snippets/remix/app/routes/custom-child.tsx
/**
 * Quickstart snippet
 * snippets/react/routes/custom-child.tsx
 */

import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type BuilderContent,
} from '@builder.io/sdk-react';
import { useEffect, useState } from 'react';
import { customHeroInfo } from '../components/CustomHero';

const BUILDER_API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
const MODEL_NAME = 'page';

export default function CustomChildRoute() {
  const [notFound, setNotFound] = useState(false);
  const [content, setContent] = useState<BuilderContent | null>(null);

  // get the page content from Builder
  useEffect(() => {
    fetchOneEntry({
      model: MODEL_NAME,
      apiKey: BUILDER_API_KEY,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    })
      .then((content) => {
        if (content) {
          setContent(content);
        }
        setNotFound(!content);
      })
      .catch((err) => {
        console.log('Oops: ', err);
      });
  }, []);

  // If no page is found, return
  // a 404 page from your code.
  if (notFound && !isPreviewing()) {
    return <div>404</div>;
  }

  // return the page when found
  return (
    <Content
      content={content}
      model={MODEL_NAME}
      apiKey={BUILDER_API_KEY}
      customComponents={[customHeroInfo]}
    />
  );
}

// packages/sdks/snippets/vue/src/views/CustomChild.vue
<template>
  <div>
    <div v-if="notFound && !isPreviewing()">404 - Not Found</div>

    <Content
      v-else
      :content="content"
      :model="pageModel"
      :apiKey="apiKey"
      :customComponents="[customHeroInfo]"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type BuilderContent
} from '@builder.io/sdk-vue';

import { customHeroInfo } from '@/components/custom-components/custom-hero/CustomHeroInfo';

const pageModel = 'page';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const content = ref<BuilderContent | null>(null);
const notFound = ref(false);

onMounted(async () => {
  try {
    const fetchedContent = await fetchOneEntry({
      model: pageModel,
      apiKey,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    });
    if (fetchedContent) {
      content.value = fetchedContent;
    } else {
      notFound.value = true;
    }
  } catch (err) {
    console.error('Oops: ', err);
  }
});
</script>
