// packages/sdks/output/angular/src-copy-fast-diff/components/block/components/interactive-element.ts
import {
  Component,
  ViewChild,
  ElementRef,
  Input,
  ViewContainerRef,
  TemplateRef,
} from "@angular/core";
import { CommonModule } from "@angular/common";

export type InteractiveElementProps = {
  Wrapper: any;
  block: BuilderBlock;
  context: BuilderContextInterface;
  wrapperProps: Dictionary<any>;
  includeBlockProps: boolean;
  children?: any;
};

import type { BuilderContextInterface } from "../../../context/types";
import { getBlockActions } from "../../../functions/get-block-actions";
import { getBlockProperties } from "../../../functions/get-block-properties";
import type { BuilderBlock } from "../../../types/builder-block";
import type { Dictionary } from "../../../types/typescript";

@Component({
  selector: "interactive-element, InteractiveElement",
  template: `
    <ng-template #wrapperTemplate><ng-content></ng-content></ng-template>
    <ng-container
      *ngComponentOutlet="
              Wrapper;
              inputs: mergedInputs_atkjh2;
              content: myContent;
              "
    ></ng-container>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class InteractiveElement {
  @Input() includeBlockProps!: InteractiveElementProps["includeBlockProps"];
  @Input() block!: InteractiveElementProps["block"];
  @Input() context!: InteractiveElementProps["context"];
  @Input() wrapperProps!: InteractiveElementProps["wrapperProps"];
  @Input() Wrapper!: InteractiveElementProps["Wrapper"];

  @ViewChild("wrapperTemplate", { static: true })
  wrapperTemplateRef!: TemplateRef<any>;

  myContent?: any[][];

  get attributes() {
    return this.includeBlockProps
      ? {
          ...getBlockProperties({
            block: this.block,
            context: this.context,
          }),
          ...getBlockActions({
            block: this.block,
            rootState: this.context.rootState,
            rootSetState: this.context.rootSetState,
            localState: this.context.localState,
            context: this.context.context,
          }),
        }
      : {};
  }
  mergedInputs_atkjh2 = null;

  constructor(private vcRef: ViewContainerRef) {}

  ngOnInit() {
    this.mergedInputs_atkjh2 = {
      ...this.wrapperProps,
      attributes: this.attributes,
    };

    this.myContent = [
      this.vcRef.createEmbeddedView(this.wrapperTemplateRef).rootNodes,
    ];
  }
}

// examples/react-v2/src/sdk-src/components/block/components/interactive-element.tsx
import * as React from "react";

export type InteractiveElementProps = {
  Wrapper: any;
  block: BuilderBlock;
  context: BuilderContextInterface;
  wrapperProps: Dictionary<any>;
  includeBlockProps: boolean;
  children?: any;
};
import type { BuilderContextInterface } from "../../../context/types.js";
import { getBlockActions } from "../../../functions/get-block-actions.js";
import { getBlockProperties } from "../../../functions/get-block-properties.js";
import type { BuilderBlock } from "../../../types/builder-block.js";
import type { Dictionary } from "../../../types/typescript.js";

function InteractiveElement(props: InteractiveElementProps) {
  function attributes() {
    return props.includeBlockProps
      ? {
          ...getBlockProperties({
            block: props.block,
            context: props.context,
          }),
          ...getBlockActions({
            block: props.block,
            rootState: props.context.rootState,
            rootSetState: props.context.rootSetState,
            localState: props.context.localState,
            context: props.context.context,
          }),
        }
      : {};
  }

  return (
    <props.Wrapper {...props.wrapperProps} attributes={attributes()}>
      {props.children}
    </props.Wrapper>
  );
}

export default InteractiveElement;
