// examples/react-native/src/sdk-working/src/context/builder.context.js
import { createContext } from "react";
var stdin_default = createContext({
  content: null,
  context: {},
  localState: void 0,
  rootSetState() {
  },
  rootState: {},
  apiKey: null,
  apiVersion: void 0,
  registeredComponents: {},
  inheritedStyles: {}
});
export {
  stdin_default as default
};

// packages/sdks/output/angular/src-original/context/builder.context.ts
import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export default class BuilderContext {
  content: any = null;
  context: any = {};
  localState: any = undefined;
  rootSetState() {}
  rootState: any = {};
  apiKey: any = null;
  apiVersion: any = undefined;
  componentInfos: any = {};
  inheritedStyles: any = {};
  BlocksWrapper: any = "div";
  BlocksWrapperProps: any = {};
  nonce: any = "";

  constructor() {}
}
