// packages/sdks/snippets/angular-16/src/app/catch-all/catch-all.component.ts
/**
 * Quickstart snippet
 * snippets/angular/src/app/catch-all/catch-all.component.ts
 */

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type BuilderContent,
} from '@builder.io/sdk-angular';

@Component({
  selector: 'app-catchall',
  standalone: true,
  imports: [Content, CommonModule],
  template: `
    <ng-container *ngIf="!notFound">
      <builder-content
        [model]="model"
        [content]="content"
        [apiKey]="apiKey"
      ></builder-content>
    </ng-container>

    <ng-template #notFound>
      <div>404 - Content not found</div>
    </ng-template>
  `,
})
export class CatchAllComponent {
  apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
  model = 'page';
  content: BuilderContent | null = null;
  notFound = false;

  async ngOnInit() {
    const urlPath = window.location.pathname || '';

    const content = await fetchOneEntry({
      apiKey: this.apiKey,
      model: this.model,
      userAttributes: {
        urlPath,
      },
    });

    this.content = content;
    this.notFound = !content && !isPreviewing();
  }
}

// packages/sdks/snippets/svelte/src/components/CatchAll.svelte
<!-- Quickstart snippet -->
<!-- snippets/svelte/src/components/CatchAll.svelte -->

<script lang="ts">
  import {
    Content,
    fetchOneEntry,
    type BuilderContent,
    isPreviewing,
  } from '@builder.io/sdk-svelte';

  let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
  let model = 'page';

  let content: BuilderContent | null = null;
  let canShowContent = false;

  async function fetchContent() {
    content = await fetchOneEntry({
      apiKey,
      model,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    });
    canShowContent = content ? true : isPreviewing();
  }

  fetchContent();
</script>

<svelte:head>
  <title>{content?.data?.title || 'Unpublished'}</title>
</svelte:head>

<main>
  {#if canShowContent}
    <Content {content} {apiKey} {model} />
  {:else}
    Content Not Found
  {/if}
</main>
