// packages/react/src/blocks/Button/Button.tsx
import React from 'react';
import { Link } from '../../components/Link';

export interface ButtonProps {
  attributes?: any;
  text?: string;
  link?: string;
  openLinkInNewTab?: boolean;
}

export const ButtonComponent : React.FC<ButtonProps> = (props) => {
  const Tag = props.link ? Link : 'span';
  return (
    <Tag
      role="button"
      href={props.link}
      target={props.openLinkInNewTab ? '_blank' : undefined}
      {...props.attributes}
    >
      {props.text}
    </Tag>
  );
}

// packages/sdks/output/svelte/src/blocks/button.svelte
<script>
  
  
  
  




  
  export let attributes;
export let text;
export let link;
export let openLinkInNewTab;

  
  

  

  

  

  
</script>


  
{#if link }
    
<a {...attributes} role="button"  href={link}  target={openLinkInNewTab ? '_blank' : undefined} >
      
{text}

    </a>

  {/if}
