// packages/sdks/output/solid/src/blocks/input/input.jsx
import { isEditing } from "../../functions/is-editing.js";

function FormInputComponent(props) {
  return <input {...props.attributes} key={isEditing() && props.defaultValue ? props.defaultValue : "default-key"} placeholder={props.placeholder} type={props.type} name={props.name} value={props.value} defaultValue={props.defaultValue} required={props.required} />;
}

export default FormInputComponent;

// packages/sdks/output/svelte/src/blocks/input.svelte
<script>
  
  
  
  
import  {  isEditing  }  from '../functions/is-editing';




  
  export let attributes;
export let defaultValue;
export let placeholder;
export let type;
export let name;
export let value;
export let required;

  
  

  

  

  

  
</script>

<input {...attributes} key={isEditing() && defaultValue ? defaultValue : 'default-key'}  placeholder={placeholder}  type={type}  name={name}  value={value}  defaultValue={defaultValue}  required={required}  />
