// examples/next-app-dir/src/sdk-src/blocks/input/input.tsx
'use client'
import * as React from 'react'

export interface FormInputProps {
  type?: string
  attributes?: any
  name?: string
  value?: string
  placeholder?: string
  defaultValue?: string
  required?: boolean
}

import { isEditing } from '../../functions/is-editing'

function FormInputComponent(props: FormInputProps) {
  return (
    <input
      {...props.attributes}
      key={
        isEditing() && props.defaultValue ? props.defaultValue : 'default-key'
      }
      placeholder={props.placeholder}
      type={props.type}
      name={props.name}
      value={props.value}
      defaultValue={props.defaultValue}
      required={props.required}
    />
  )
}

export default FormInputComponent

// packages/sdks/output/svelte/src/blocks/input.svelte
<script>
  
  
  
  
import  {  isEditing  }  from '../functions/is-editing';




  
  export let attributes;
export let defaultValue;
export let placeholder;
export let type;
export let name;
export let value;
export let required;

  
  

  

  

  

  
</script>

<input {...attributes} key={isEditing() && defaultValue ? defaultValue : 'default-key'}  placeholder={placeholder}  type={type}  name={name}  value={value}  defaultValue={defaultValue}  required={required}  />
