// packages/sdks/output/react-native/src/blocks/symbol.lite.tsx
import * as React from 'react';
import { View, StyleSheet, Image, Text } from 'react-native';
import { useState, useContext, useEffect } from 'react';
import RenderContent from '../components/render-content.lite';
import BuilderContext from '../context/builder.context.lite';
import { getContent } from '../functions/get-content';

export default function Symbol(props) {
  const [className, setClassName] = useState(() => 'builder-symbol');

  const [content, setContent] = useState(() => null);

  const builderContext = useContext(BuilderContext);

  useEffect(() => {
    setContent(props.symbol?.content);
  }, []);

  useEffect(() => {
    const symbol = props.symbol;

    if (symbol && !symbol.content && !content && symbol.model) {
      getContent({
        model: symbol.model,
        apiKey: builderContext.apiKey,
        options: {
          entry: symbol.entry,
        },
      }).then((response) => {
        setContent(response);
      });
    }
  }, [
    props.symbol?.content,
    props.symbol?.model,
    props.symbol?.entry,
    content,
  ]);

  return (
    <View
      {...props.attributes}
      dataSet={{
        class: className,
      }}
    >
      <RenderContent
        apiKey={builderContext.apiKey}
        context={builderContext.context}
        data={{
          ...props.symbol?.data,
          ...builderContext.state,
          ...props.symbol?.content?.data?.state,
        }}
        model={props.symbol?.model}
        content={content}
      />
    </View>
  );
}

// packages/sdks/output/svelte/src/blocks/symbol.lite.tsx
<script>
  import { onMount } from "svelte";
  import { afterUpdate } from "svelte";

  import RenderContent from "../components/render-content.lite";
  import BuilderContext from "../context/builder.context.lite";
  import { getContent } from "../functions/get-content";

  export let attributes;
  export let symbol;

  let className = "builder-symbol";
  let content = null;

  onMount(() => {
    content = symbol?.content;
  });

  afterUpdate(() => {
    const symbol = symbol;

    if (symbol && !symbol.content && !content && symbol.model) {
      getContent({
        model: symbol.model,
        apiKey: builderContext.apiKey!,
        options: {
          entry: symbol.entry,
        },
      }).then((response) => {
        content = response;
      });
    }
  });

</script>

<div
  {...attributes}
  dataSet={{ class: className }}
  class={className}>
  <RenderContent
    apiKey={builderContext.apiKey}
    context={builderContext.context}
    data={{ ...symbol?.data, ...builderContext.state, ...symbol?.content?.data?.state }}
    model={symbol?.model}
    {content} />
</div>
