// examples/react-native/src/sdk-working/src/blocks/textarea/textarea.jsx
import * as React from "react";
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
} from "react-native";

function Textarea(props) {
  return (
    <View
      {...props.attributes}
      placeholder={props.placeholder}
      name={props.name}
      value={props.value}
      defaultValue={props.defaultValue}
    />
  );
}

export default Textarea;

// packages/sdks/output/svelte/src/blocks/textarea.svelte
<script>
  
  
  
  



  

  
  export let attributes;
export let placeholder;
export let name;
export let value;
export let defaultValue;
  
  
  

  
  
  

  

  

  
</script>

<textarea {...attributes} placeholder={placeholder}  name={name}  value={value}  defaultValue={defaultValue} ></textarea>
