// packages/sdks/snippets/hydrogen/app/routes/marketing-event.tsx
import {fetchOneEntry, Content, isPreviewing} from '@builder.io/sdk-react';
import {useLoaderData} from '@remix-run/react';
import {type LoaderFunction} from '@shopify/remix-oxygen';

const MODEL = 'collection-hero';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export const loader: LoaderFunction = async ({params}) => {
  const content = await fetchOneEntry({
    model: MODEL,
    apiKey: API_KEY,
    userAttributes: {urlPath: params.pathname},
  });

  return {content};
};

export default function ProductHero() {
  const {content} = useLoaderData<typeof loader>();

  return (
    <div>
      {/* Your nav goes here */}
      {/* Hero Section */}
      <Content model={MODEL} content={content} apiKey={API_KEY} />
      {/* The rest of your page goes here */}
    </div>
  );
}

// packages/sdks/snippets/qwik-city/src/routes/marketing-event/index.tsx
import { component$ } from '@builder.io/qwik';
import { routeLoader$ } from '@builder.io/qwik-city';
import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-qwik';

const MODEL = 'collection-hero';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export const useProductHero = routeLoader$(async ({ url }) => {
  return await fetchOneEntry({
    model: MODEL,
    apiKey: API_KEY,
    userAttributes: {
      urlPath: url.pathname,
    },
  });
});

export default component$(() => {
  const productHero = useProductHero();

  return (
    <>
      {/* Your nav goes here */}
      {/* Hero Section */}
      {productHero.value || isPreviewing() ? (
        <Content model={MODEL} content={productHero.value} apiKey={API_KEY} />
      ) : (
        <div>404</div>
      )}
      {/* The rest of your page goes here */}
    </>
  );
});
