// packages/sdks/examples/vue/src/App.vue
<template>
  <Content
    v-if="canShowContent"
    model="page"
    :content="content"
    :api-key="apiKey"
  />
</template>

<script>
import {
  fetchOneEntry,
  Content,
  isPreviewing,
  getBuilderSearchParams,
} from '@builder.io/sdk-vue';

export default {
  components: {
    Content,
  },
  data: () => ({
    canShowContent: false,
    content: null,
    apiKey: '75515d9050724317bfaeb81ca89328c9',
  }),
  mounted() {
    fetchOneEntry({
      model: 'page',
      apiKey: this.apiKey,
      options: getBuilderSearchParams(new URL(location.href).searchParams),
      userAttributes: {
        urlPath: window.location.pathname,
      },
    }).then((res) => {
      this.content = res;
      this.canShowContent = this.content || isPreviewing();
    });
  },
};
</script>

// packages/sdks/snippets/nextjs-app-dir-client/app/page.tsx
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  getBuilderSearchParams,
} from '@builder.io/sdk-react/edge';

interface PageProps {
  params: {
    slug: string[];
  };
  searchParams: Record<string, string>;
}

const PUBLIC_API_KEY = 'f1a790f8c3204b3b8c5c1795aeac4660';

export default async function Page(props: PageProps) {
  const content = await fetchOneEntry({
    options: getBuilderSearchParams(props.searchParams),
    apiKey: PUBLIC_API_KEY,
    model: 'page',
    userAttributes: { urlPath: '/' },
  });

  const canShowContent = content || isPreviewing(props.searchParams);

  if (!canShowContent) {
    return (
      <>
        <h1>404</h1>
        <p>Make sure you have your content published at Builder.io.</p>
      </>
    );
  }
  return <Content content={content} apiKey={PUBLIC_API_KEY} model="page" />;
}
