// packages/sdks/output/solid/src/blocks/select/select.lite.tsx
import { For } from "solid-js";

import { isEditing } from "../../functions/is-editing";

function SelectComponent(props) {
  return (
    <select
      {...props.attributes}
      value={props.value}
      key={
        isEditing() && props.defaultValue ? props.defaultValue : "default-key"
      }
      defaultValue={props.defaultValue}
      name={props.name}
    >
      <For each={props.options}>
        {(option, _index) => {
          const index = _index();
          return (
            <option value={option.value}>{option.name || option.value}</option>
          );
        }}
      </For>
    </select>
  );
}

export default SelectComponent;

// packages/sdks/src/blocks/select.lite.tsx
import { For } from '@builder.io/mitosis';
import { isEditing } from '../functions/is-editing';

export interface FormSelectProps {
  options?: { name?: string; value: string }[];
  attributes?: any;
  name?: string;
  value?: string;
  defaultValue?: string;
}

export default function SelectComponent(props: FormSelectProps) {
  return (
    <select
      {...props.attributes}
      value={props.value}
      key={
        isEditing() && props.defaultValue ? props.defaultValue : 'default-key'
      }
      defaultValue={props.defaultValue}
      name={props.name}
    >
      <For each={props.options}>
        {(option) => (
          <option value={option.value}>{option.name || option.value}</option>
        )}
      </For>
    </select>
  );
}
