// packages/sdks/output/solid/src/components/render-inlined-styles.lite.tsx
import { Show } from "solid-js";
import { Dynamic } from "solid-js/web";
import { createMutable } from "solid-js/store";

import { TARGET } from "../constants/target.js";

function RenderInlinedStyles(props) {
  const state = createMutable({
    get injectedStyleScript() {
      return `<${state.tagName}>${props.styles}</${state.tagName}>`;
    },
    get tagName() {
      // NOTE: we have to obfusctate the name of the tag due to a limitation in the svelte-preprocessor plugin.
      // https://github.com/sveltejs/vite-plugin-svelte/issues/315#issuecomment-1109000027
      return "sty" + "le";
    },
  });

  return (
    <Show when={TARGET === "svelte"}>
      <div innerHTML={state.injectedStyleScript}></div>
    </Show>
  );
}

export default RenderInlinedStyles;

// packages/sdks/src/components/render-inlined-styles.lite.tsx
import { TARGET } from '../constants/target.js';
import { Show, useState } from '@builder.io/mitosis';

interface Props {
  styles: string;
}

export default function RenderInlinedStyles(props: Props) {
  const state = useState({
    get injectedStyleScript(): string {
      return `<${state.tagName}>${props.styles}</${state.tagName}>`;
    },
    get tagName(): string {
      // NOTE: we have to obfusctate the name of the tag due to a limitation in the svelte-preprocessor plugin.
      // https://github.com/sveltejs/vite-plugin-svelte/issues/315#issuecomment-1109000027
      return 'sty' + 'le';
    },
  });

  return (
    <Show
      when={TARGET === 'svelte'}
      else={<state.tagName>{props.styles}</state.tagName>}
    >
      {/**
       * We have a Svelte plugin that converts this `div` to a `Fragment`. We cannot directly use a "Fragment" here because
       * not all frameworks support providing properties to a "Fragment" (e.g. Solid)
       */}
      <div innerHTML={state.injectedStyleScript} />
    </Show>
  );
}
