// examples/react-v2/src/sdk-src/components/block/components/repeated-block.tsx
"use client";
import * as React from "react";
import { useState, useContext } from "react";

type Props = Omit<BlockProps, "context"> & {
  repeatContext: BuilderContextInterface;
};
import BuilderContext from "../../../context/builder.context.js";
import type { BuilderContextInterface } from "../../../context/types.js";
import type { BlockProps } from "../block";
import Block from "../block";

function RepeatedBlock(props: Props) {
  const [store, setStore] = useState(() => props.repeatContext);

  return (
    <BuilderContext.Provider value={store}>
      <Block
        block={props.block}
        context={store}
        registeredComponents={props.registeredComponents}
        linkComponent={props.linkComponent}
      />
    </BuilderContext.Provider>
  );
}

export default RepeatedBlock;

// packages/sdks/output/angular/src/components/block/components/repeated-block.ts
import { Component, Input ,forwardRef } from "@angular/core";
import { CommonModule } from "@angular/common";

type Props = Omit<BlockProps, "context"> & {
  repeatContext: BuilderContextInterface;
};

import BuilderContext from "../../../context/builder.context";
import type { BuilderContextInterface } from "../../../context/types";
import type { BlockProps } from "../block";
import Block from "../block";

@Component({
  selector: "repeated-block, RepeatedBlock",
  template: `
    <block
      [block]="block"
      [context]="store"
      [registeredComponents]="registeredComponents"
      [linkComponent]="linkComponent"
    ></block>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, forwardRef(() => Block)],
})
export default class RepeatedBlock {
  @Input() repeatContext!: Props["repeatContext"];
  @Input() block!: Props["block"];
  @Input() registeredComponents!: Props["registeredComponents"];
  @Input() linkComponent!: Props["linkComponent"];

  store = this.repeatContext;
}
