// packages/sdks/output/solid/src/components/render-content/render-content.lite.tsx
import { useContext, Show, onMount } from "solid-js";
import { Dynamic } from "solid-js/web";
import { createMutable } from "solid-js/store";

import { getDefaultRegisteredComponents } from "../../constants/builder-registered-components.js";
import { TARGET } from "../../constants/target.js";
import BuilderContext from "../../context/builder.context";
import { evaluate } from "../../functions/evaluate.js";
import {
  convertSearchParamsToQueryObject,
  getBuilderSearchParams,
} from "../../functions/get-builder-search-params/index.js";
import { getContent } from "../../functions/get-content/index.js";
import { getFetch } from "../../functions/get-fetch.js";
import { isBrowser } from "../../functions/is-browser.js";
import { isEditing } from "../../functions/is-editing.js";
import { isPreviewing } from "../../functions/is-previewing.js";
import { previewingModelName } from "../../functions/previewing-model-name.js";
import {
  components,
  createRegisterComponentMessage,
} from "../../functions/register-component.js";
import { track } from "../../functions/track.js";
import RenderBlocks from "../render-blocks.lite";
import RenderContentStyles from "./components/render-styles.lite";

function RenderContent(props) {
  const state = createMutable({
    get useContent() {
      const mergedContent: BuilderContent = {
        ...props.content,
        ...state.overrideContent,
        data: {
          ...props.content?.data,
          ...props.data,
          ...state.overrideContent?.data,
        },
      };
      return mergedContent;
    },
    overrideContent: null,
    update: 0,
    overrideState: {},
    get contentState() {
      return {
        ...props.content?.data?.state,
        ...props.data,
        ...state.overrideState,
      };
    },
    get context() {
      return {} as Dictionary<any>;
    },
    get allRegisteredComponents() {
      const allComponentsArray = [
        ...getDefaultRegisteredComponents(), // While this `components` object is deprecated, we must maintain support for it.
        // Since users are able to override our default components, we need to make sure that we do not break such
        // existing usage.
        // This is why we spread `components` after the default Builder.io components, but before the `props.customComponents`,
        // which is the new standard way of providing custom components, and must therefore take precedence.
        ...components,
        ...(props.customComponents || []),
      ];
      const allComponents = allComponentsArray.reduce(
        (acc, curr) => ({ ...acc, [curr.name]: curr }),
        {} as RegisteredComponents
      );
      return allComponents;
    },
    processMessage(event: MessageEvent) {
      const { data } = event;

      if (data) {
        switch (data.type) {
          case "builder.contentUpdate": {
            const messageContent = data.data;
            const key =
              messageContent.key ||
              messageContent.alias ||
              messageContent.entry ||
              messageContent.modelName;
            const contentData = messageContent.data;

            if (key === props.model) {
              state.overrideContent = contentData;
            }

            break;
          }

          case "builder.patchUpdates": {
            // TODO
            break;
          }
        }
      }
    },
    evaluateJsCode() {
      // run any dynamic JS code attached to content
      const jsCode = state.useContent?.data?.jsCode;

      if (jsCode) {
        evaluate({
          code: jsCode,
          context: state.context,
          state: state.contentState,
        });
      }
    },
    get httpReqsData() {
      return {};
    },
    evalExpression(expression: string) {
      return expression.replace(/{{([^}]+)}}/g, (_match, group) =>
        evaluate({
          code: group,
          context: state.context,
          state: state.contentState,
        })
      );
    },
    handleRequest({ url, key }: { key: string; url: string }) {
      const fetchAndSetState = async () => {
        const fetch = await getFetch();
        const response = await fetch(url);
        const json = await response.json();
        const newOverrideState = { ...state.overrideState, [key]: json };
        state.overrideState = newOverrideState;
      };

      fetchAndSetState();
    },
    runHttpRequests() {
      const requests = state.useContent?.data?.httpRequests ?? {};
      Object.entries(requests).forEach(([key, url]) => {
        if (url && (!state.httpReqsData[key] || isEditing())) {
          const evaluatedUrl = state.evalExpression(url);
          state.handleRequest({
            url: evaluatedUrl,
            key,
          });
        }
      });
    },
    emitStateUpdate() {
      if (isEditing()) {
        window.dispatchEvent(
          new CustomEvent<BuilderComponentStateChange>(
            "builder:component:stateChange",
            {
              detail: {
                state: state.contentState,
                ref: {
                  name: props.model,
                },
              },
            }
          )
        );
      }
    },
  });

  onMount(() => {
    if (isBrowser()) {
      if (isEditing()) {
        Object.values(state.allRegisteredComponents).forEach(
          (registeredComponent) => {
            const message = createRegisterComponentMessage(registeredComponent);
            window.parent?.postMessage(message, "*");
          }
        );
        window.addEventListener("message", state.processMessage);
        window.addEventListener(
          "builder:component:stateChangeListenerActivated",
          state.emitStateUpdate
        );
      }

      if (state.useContent) {
        track("impression", {
          contentId: state.useContent.id,
        });
      } // override normal content in preview mode

      if (isPreviewing()) {
        if (props.model && previewingModelName() === props.model) {
          const currentUrl = new URL(location.href);
          const previewApiKey = currentUrl.searchParams.get("apiKey");

          if (previewApiKey) {
            getContent({
              model: props.model,
              apiKey: previewApiKey,
              options: getBuilderSearchParams(
                convertSearchParamsToQueryObject(currentUrl.searchParams)
              ),
            }).then((content) => {
              if (content) {
                state.overrideContent = content;
              }
            });
          }
        }
      }

      state.evaluateJsCode();
      state.runHttpRequests();
      state.emitStateUpdate();
    }
  });

  return (
    <Dynamic
      value={{
        get content() {
          return state.useContent;
        },
        get state() {
          return state.contentState;
        },
        get context() {
          return state.context;
        },
        get apiKey() {
          return props.apiKey;
        },
        get registeredComponents() {
          return state.allRegisteredComponents;
        },
      }}
      component={BuilderContext.Provider}
    >
      <Show when={state.useContent}>
        <div
          onClick={(event) =>
            track("click", {
              contentId: state.useContent.id,
            })
          }
          data-builder-content-id={state.useContent?.id}
        >
          <Show
            when={
              (state.useContent?.data?.cssCode ||
                state.useContent?.data?.customFonts?.length) &&
              TARGET !== "reactNative"
            }
          >
            <RenderContentStyles
              cssCode={state.useContent.data.cssCode}
              customFonts={state.useContent.data.customFonts}
            ></RenderContentStyles>
          </Show>
          <RenderBlocks blocks={state.useContent?.data?.blocks}></RenderBlocks>
        </div>
      </Show>
    </Dynamic>
  );
}

export default RenderContent;

// packages/sdks/output/react-native/src/components/render-content/render-content.lite.tsx
import * as React from "react";
import { View, StyleSheet, Image, Text } from "react-native";
import { useState, useContext, useEffect } from "react";
import { getDefaultRegisteredComponents } from "../../constants/builder-registered-components.js";
import { TARGET } from "../../constants/target.js";
import BuilderContext from "../../context/builder.context";
import { evaluate } from "../../functions/evaluate.js";
import {
  convertSearchParamsToQueryObject,
  getBuilderSearchParams,
} from "../../functions/get-builder-search-params/index.js";
import { getContent } from "../../functions/get-content/index.js";
import { getFetch } from "../../functions/get-fetch.js";
import { isBrowser } from "../../functions/is-browser.js";
import { isEditing } from "../../functions/is-editing.js";
import { isPreviewing } from "../../functions/is-previewing.js";
import { previewingModelName } from "../../functions/previewing-model-name.js";
import {
  components,
  createRegisterComponentMessage,
} from "../../functions/register-component.js";
import { track } from "../../functions/track.js";
import RenderBlocks from "../render-blocks.lite";
import RenderContentStyles from "./components/render-styles.lite";

export default function RenderContent(props) {
  function useContent() {
    const mergedContent = {
      ...props.content,
      ...overrideContent,
      data: { ...props.content?.data, ...props.data, ...overrideContent?.data },
    };
    return mergedContent;
  }

  const [overrideContent, setOverrideContent] = useState(() => null);

  const [update, setUpdate] = useState(() => 0);

  const [overrideState, setOverrideState] = useState(() => ({}));

  function contentState() {
    return { ...props.content?.data?.state, ...props.data, ...overrideState };
  }

  function context() {
    return {};
  }

  function allRegisteredComponents() {
    const allComponentsArray = [
      ...getDefaultRegisteredComponents(), // While this `components` object is deprecated, we must maintain support for it.
      // Since users are able to override our default components, we need to make sure that we do not break such
      // existing usage.
      // This is why we spread `components` after the default Builder.io components, but before the `props.customComponents`,
      // which is the new standard way of providing custom components, and must therefore take precedence.
      ...components,
      ...(props.customComponents || []),
    ];
    const allComponents = allComponentsArray.reduce(
      (acc, curr) => ({ ...acc, [curr.name]: curr }),
      {}
    );
    return allComponents;
  }

  function processMessage(event) {
    const { data } = event;

    if (data) {
      switch (data.type) {
        case "builder.contentUpdate": {
          const messageContent = data.data;
          const key =
            messageContent.key ||
            messageContent.alias ||
            messageContent.entry ||
            messageContent.modelName;
          const contentData = messageContent.data;

          if (key === props.model) {
            setOverrideContent(contentData);
          }

          break;
        }

        case "builder.patchUpdates": {
          // TODO
          break;
        }
      }
    }
  }

  function evaluateJsCode() {
    // run any dynamic JS code attached to content
    const jsCode = useContent?.()?.data?.jsCode;

    if (jsCode) {
      evaluate({
        code: jsCode,
        context: context(),
        state: contentState(),
      });
    }
  }

  function httpReqsData() {
    return {};
  }

  function evalExpression(expression) {
    return expression.replace(/{{([^}]+)}}/g, (_match, group) =>
      evaluate({
        code: group,
        context: context(),
        state: contentState(),
      })
    );
  }

  function handleRequest({ url, key }) {
    const fetchAndSetState = async () => {
      const fetch = await getFetch();
      const response = await fetch(url);
      const json = await response.json();
      const newOverrideState = { ...overrideState, [key]: json };
      setOverrideState(newOverrideState);
    };

    fetchAndSetState();
  }

  function runHttpRequests() {
    const requests = useContent?.()?.data?.httpRequests ?? {};
    Object.entries(requests).forEach(([key, url]) => {
      if (url && (!httpReqsData()[key] || isEditing())) {
        const evaluatedUrl = evalExpression(url);
        handleRequest({
          url: evaluatedUrl,
          key,
        });
      }
    });
  }

  function emitStateUpdate() {
    if (isEditing()) {
      window.dispatchEvent(
        new CustomEvent("builder:component:stateChange", {
          detail: {
            state: contentState(),
            ref: {
              name: props.model,
            },
          },
        })
      );
    }
  }

  useEffect(() => {
    if (isBrowser()) {
      if (isEditing()) {
        Object.values(allRegisteredComponents()).forEach(
          (registeredComponent) => {
            const message = createRegisterComponentMessage(registeredComponent);
            window.parent?.postMessage(message, "*");
          }
        );
        window.addEventListener("message", processMessage);
        window.addEventListener(
          "builder:component:stateChangeListenerActivated",
          emitStateUpdate
        );
      }

      if (useContent()) {
        track("impression", {
          contentId: useContent().id,
        });
      } // override normal content in preview mode

      if (isPreviewing()) {
        if (props.model && previewingModelName() === props.model) {
          const currentUrl = new URL(location.href);
          const previewApiKey = currentUrl.searchParams.get("apiKey");

          if (previewApiKey) {
            getContent({
              model: props.model,
              apiKey: previewApiKey,
              options: getBuilderSearchParams(
                convertSearchParamsToQueryObject(currentUrl.searchParams)
              ),
            }).then((content) => {
              if (content) {
                setOverrideContent(content);
              }
            });
          }
        }
      }

      evaluateJsCode();
      runHttpRequests();
      emitStateUpdate();
    }
  }, []);

  useEffect(() => {
    evaluateJsCode();
  }, [useContent?.()?.data?.jsCode]);
  useEffect(() => {
    runHttpRequests();
  }, [useContent?.()?.data?.httpRequests]);
  useEffect(() => {
    emitStateUpdate();
  }, [contentState()]);

  useEffect(() => {
    return () => {
      if (isBrowser()) {
        window.removeEventListener("message", processMessage);
        window.removeEventListener(
          "builder:component:stateChangeListenerActivated",
          emitStateUpdate
        );
      }
    };
  }, []);

  return (
    <BuilderContext.Provider
      value={{
        get content() {
          return useContent();
        },

        get state() {
          return contentState();
        },

        get context() {
          return context();
        },

        get apiKey() {
          return props.apiKey;
        },

        get registeredComponents() {
          return allRegisteredComponents();
        },
      }}
    >
      {useContent() ? (
        <>
          <View
            onClick={(event) =>
              track("click", {
                contentId: useContent().id,
              })
            }
            data-builder-content-id={useContent?.()?.id}
          >
            {(useContent?.()?.data?.cssCode ||
              useContent?.()?.data?.customFonts?.length) &&
            TARGET !== "reactNative" ? (
              <RenderContentStyles
                cssCode={useContent().data.cssCode}
                customFonts={useContent().data.customFonts}
              />
            ) : null}

            <RenderBlocks blocks={useContent?.()?.data?.blocks} />
          </View>
        </>
      ) : null}
    </BuilderContext.Provider>
  );
}
